#!/bin/bash
set -e
export XDG_RUNTIME_DIR=/run/user/$(id -u)
export XDG_SESSION_TYPE=wayland XDG_SESSION_DESKTOP=KDE XDG_CURRENT_DESKTOP=KDE DESKTOP_SESSION=plasmawayland
export XDG_SESSION_CLASS=user XDG_SEAT=seat0 XDG_VTNR=1 KDE_FULL_SESSION=true KDE_SESSION_VERSION=5
export LIBGL_ALWAYS_SOFTWARE=0 GALLIUM_DRIVER=virgl
export GDK_BACKEND=wayland QT_QPA_PLATFORM=wayland CLUTTER_BACKEND=wayland SDL_VIDEODRIVER=wayland
export MOZ_ENABLE_WAYLAND=1 MOZ_WEBRENDER=1 MOZ_ACCELERATED=1
unset DISPLAY MOZ_X11_EGL
exec startplasma-wayland
