#!/usr/bin/env python3
"""Vessel protocol 38: UML virtio-gpu -> VirGL -> ANGLE/Vulkan -> Adreno.

This runtime replaces the old Weston/Venus protocol-37 stack. It owns the same
persistent Debian ext4 disk and control channel, but boots the standard Linux
virtio-gpu DRM frontend through VIRTIO_UML/vhost-user.

For the first end-to-end Android Surface validation it launches kmscube directly
on /dev/dri/card0. That gives us a real Linux DRM/KMS scanout generated by the
accelerated VirGL renderer, with no VNC, screenshot polling, nested Weston or
Termux:X11 involved.
"""
from __future__ import annotations

import json
import pathlib
import socket
import threading
import time
from typing import Any

import vessel_runtime_daemon_v33 as v33

PROTOCOL_VERSION = 38
RUNTIME_REVISION = "v38-virtio-gpu-virgl-adreno"
DISPLAY_TRANSPORT = "virtio-gpu-rgb-loopback-android-vulkan-v1"
POC = pathlib.Path.home() / "vessel-poc-runtime"
if "VESSEL_POC_DIR" in __import__("os").environ:
    POC = pathlib.Path(__import__("os").environ["VESSEL_POC_DIR"])

# Reuse the mature PTY + reverse JSON-RPC controller, but point it at the new
# virtio-gpu runner instead of the old Venus runner.
v33.v31.base.RUNNER = POC / "tools/venus_poc/run_vessel_virtio_gpu.sh"
DISPLAY_LOG = v33.v31.base.RUNTIME / "vessel-vhost-gpu-display.log"
GPU_LOG = v33.v31.base.RUNTIME / "vessel-vhost-gpu.log"


class VirtioGpuRuntime(v33.WlrootsRuntime):
    def __init__(self) -> None:
        super().__init__()
        self._desktop_worker: threading.Thread | None = None
        self._worker_lock = threading.Lock()

    def state(self) -> dict[str, Any]:
        state = super().state()
        state.update({
            "protocolVersion": PROTOCOL_VERSION,
            "runtimeRevision": RUNTIME_REVISION,
            "displayTransport": DISPLAY_TRANSPORT,
            "backend": "UML_VIRTIO_GPU",
            "presenter": "vhost-user-gpu RGB scanout -> Android Vulkan SurfaceView",
            "renderer": "Mesa VirGL -> virglrenderer -> ANGLE/Vulkan -> Adreno",
            "rendererMode": "virgl-opengl",
            "compositor": "direct DRM/KMS validation",
            "desktopName": "VirtIO GPU direct display",
            "translationLayer": "VirGL",
            "gpuOnly": True,
            "softwareFallback": False,
            "vncPort": -1,
            "frameContentValidated": bool(self.desktop_ready),
            "desktopWorkerAlive": bool(self._desktop_worker and self._desktop_worker.is_alive()),
            "displayLog": self._tail(DISPLAY_LOG, 7000),
            "gpuLog": self._tail(GPU_LOG, 7000),
        })
        return state

    @staticmethod
    def _tail(path: pathlib.Path, amount: int) -> str:
        try:
            return path.read_text(errors="replace")[-amount:]
        except Exception:
            return ""

    def _prepare_venus_guest(self) -> None:
        # Name retained because Runtime.start() calls this virtual hook. There is
        # no Venus setup here anymore.
        self.set_progress("command_agent", 36, "Starting guest control channel")
        agent = POC / "tools/venus_poc/guest_command_agent_v33.py"
        if not agent.exists():
            raise RuntimeError(f"guest command agent missing: {agent}")
        self._bootstrap_upload(agent, "/root/vessel_guest_command_agent_v38.py")
        self._pty_guest(
            f"VESSEL_COMMAND_PORT={self.command_port} "
            "nohup python3 /root/vessel_guest_command_agent_v38.py "
            ">/tmp/vessel-command-agent.log 2>&1 </dev/null &",
            20,
        )
        if not self._wait_rpc(20):
            tail = self._pty_guest("tail -120 /tmp/vessel-command-agent.log 2>/dev/null || true", 20)
            raise RuntimeError("guest command agent did not connect: " + tail[-6000:])

        self.set_progress("gpu_probe", 48, "Checking virtio-gpu DRM renderer")
        probe = self.guest(
            "test -c /dev/dri/card0 && test -c /dev/dri/renderD128 && "
            "echo VIRTIO_DRM_READY; "
            "EGL_PLATFORM=surfaceless eglinfo 2>&1 | "
            "grep -E 'EGL driver name: virtio_gpu|Device #0|EGL vendor string' | head -20 || true",
            25,
        )
        if "VIRTIO_DRM_READY" not in probe or "virtio_gpu" not in probe:
            raise RuntimeError("virtio-gpu DRM renderer did not initialize:\n" + probe[-8000:])
        self.append("VIRTIO_GPU_DRM_READY\n")
        self.set_progress("debian_ready", 55, "Debian + VirtIO GPU ready")

    def _ensure_kmscube(self) -> None:
        have = self.guest("command -v kmscube >/dev/null && echo KMSCUBE_READY || true", 10)
        if "KMSCUBE_READY" in have:
            return
        self.set_progress("display_deps", 62, "Installing direct DRM display test")
        out = self.guest(
            "export DEBIAN_FRONTEND=noninteractive; apt-get update && "
            "apt-get install -y --no-install-recommends kmscube",
            900,
        )
        check = self.guest("command -v kmscube >/dev/null && echo KMSCUBE_READY || true", 10)
        if "KMSCUBE_READY" not in check:
            raise RuntimeError("kmscube installation failed:\n" + out[-8000:])

    def ensure_desktop(self, width: int = 1280, height: int = 720, dpi: int = 120) -> dict[str, Any]:
        del dpi
        self.start()
        width = max(800, min(width, 2560))
        height = max(540, min(height, 1600))
        self._ensure_kmscube()

        self.desktop_ready = False
        self.set_progress("display_start", 75, "Starting accelerated DRM/KMS scanout")
        # Debian's kmscube treats POLLIN/HUP on stdin as "user interrupted".
        # /dev/null is therefore wrong for a daemonized launch because EOF is
        # immediately pollable. Give kmscube a private pipe whose write end it
        # keeps open itself across exec; fd 0 then stays quiet and non-EOF for
        # the lifetime of kmscube without needing another helper process.
        self.guest(
            "pkill -x kmscube 2>/dev/null || true; "
            "rm -f /tmp/vessel-kmscube.log /tmp/vessel-kmscube.pid; "
            "nohup env EGL_PLATFORM=gbm python3 -c '"
            "import os; "
            "r,w=os.pipe(); "
            "os.set_inheritable(w, True); "
            "os.dup2(r, 0); "
            "os.close(r); "
            "os.execvp(\"kmscube\", [\"kmscube\", \"-D\", \"/dev/dri/card0\"])' "
            ">/tmp/vessel-kmscube.log 2>&1 & echo $! >/tmp/vessel-kmscube.pid",
            20,
        )

        self.set_progress("display_frame", 88, "Waiting for a non-black VirtIO GPU frame")
        deadline = time.monotonic() + 75
        while time.monotonic() < deadline:
            guest = self.guest(
                "pid=$(cat /tmp/vessel-kmscube.pid 2>/dev/null || true); "
                "case \"$pid\" in ''|*[!0-9]*) ;; *) kill -0 \"$pid\" 2>/dev/null && echo KMSCUBE_ALIVE || true ;; esac",
                8,
            )
            if "KMSCUBE_ALIVE" not in guest:
                failure_log = self.guest(
                    "tail -60 /tmp/vessel-kmscube.log 2>/dev/null | cut -c1-500 || true",
                    8,
                )
                raise RuntimeError("kmscube exited before scanout:\n" + failure_log[-6000:])
            display = self._tail(DISPLAY_LOG, 12000)
            # Raw-scanout v2 never forwards an all-black readback. Therefore a
            # raw frame that reached the Android bridge is also our content
            # validation milestone, not just a transport milestone.
            if "raw frame scanout=" in display and "presenter=yes" in display:
                self.desktop_ready = True
                self.last_error = ""
                self.append("VIRTIO_GPU_FRAME_REACHED_VESSEL\n")
                self.append("VIRTIO_GPU_VALIDATED_FRAME_REACHED_VESSEL\n")
                self.set_progress("frame_validated", 96, "Validated non-black GPU frame reached Vessel")
                return self.state()
            time.sleep(.25)

        raise RuntimeError(
            "No non-black VirtIO GPU frame reached Vessel within 75s.\n"
            + "=== display ===\n" + self._tail(DISPLAY_LOG, 10000)
            + "\n=== gpu ===\n" + self._tail(GPU_LOG, 10000)
        )

    def start_desktop_async(self, width: int, height: int, dpi: int) -> dict[str, Any]:
        with self._worker_lock:
            if self._desktop_worker and self._desktop_worker.is_alive():
                return self.state()

            def worker() -> None:
                try:
                    self.ensure_desktop(width, height, dpi)
                except Exception as exc:
                    self.last_error = f"{type(exc).__name__}: {exc}"
                    self.set_progress("error", -1, self.last_error)

            self.last_error = ""
            self.set_progress("queued", 1, "Starting Vessel VirtIO GPU runtime")
            self._desktop_worker = threading.Thread(target=worker, name="vessel-v38-display", daemon=True)
            self._desktop_worker.start()
        return self.state()

    def desktop_action(self, name: str) -> dict[str, Any]:
        if name == "gpu-test":
            return self.ensure_desktop(1280, 720, 120)
        return self.state()

    def stop(self) -> dict[str, Any]:
        if self.guest_ready and self._wait_rpc(.05):
            try:
                self.guest("pkill -x kmscube 2>/dev/null || true", 8)
            except Exception:
                pass
        return super().stop()


runtime = VirtioGpuRuntime()


def handle(req: dict[str, Any]) -> dict[str, Any]:
    action = str(req.get("action", "status"))
    try:
        if action == "status":
            return runtime.state()
        if action == "start":
            return runtime.start(float(req.get("timeout", 100)))
        if action == "stop":
            return runtime.stop()
        if action == "desktop":
            return runtime.ensure_desktop(int(req.get("width", 1280)), int(req.get("height", 720)), int(req.get("dpi", 120)))
        if action == "desktopAsync":
            return runtime.start_desktop_async(int(req.get("width", 1280)), int(req.get("height", 720)), int(req.get("dpi", 120)))
        if action == "desktopAction":
            return runtime.desktop_action(str(req.get("name", "")))
        if action == "guest":
            output = runtime.guest(str(req.get("command", "")), float(req.get("timeout", 45)))
            result = runtime.state()
            result["output"] = output
            return result
        if action == "logs":
            return runtime.state()
        return {"ok": False, "error": f"unknown action: {action}"}
    except Exception as exc:
        runtime.last_error = f"{type(exc).__name__}: {exc}"
        runtime.set_progress("error", -1, runtime.last_error)
        result = runtime.state()
        result.update({"ok": False, "error": runtime.last_error})
        return result


if __name__ == "__main__":
    def serve_connection(conn: socket.socket) -> None:
        with conn:
            try:
                conn.settimeout(5)
                data = b""
                while b"\n" not in data and len(data) < 1_000_000:
                    chunk = conn.recv(65536)
                    if not chunk:
                        break
                    data += chunk
                req = json.loads(data.split(b"\n", 1)[0].decode() or "{}")
                reply = handle(req)
            except Exception as exc:
                reply = {"ok": False, "error": f"protocol: {type(exc).__name__}: {exc}"}
            try:
                conn.sendall((json.dumps(reply, separators=(",", ":")) + "\n").encode())
            except OSError:
                pass

    srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    srv.bind(("127.0.0.1", 47631))
    srv.listen(16)
    while True:
        conn, _ = srv.accept()
        threading.Thread(target=serve_connection, args=(conn,), daemon=True).start()
