package com.example.dreamlinux

import android.app.ActivityManager
import android.content.Context
import android.os.Environment
import android.system.Os
import android.system.OsConstants
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONObject
import java.io.BufferedReader
import java.io.BufferedWriter
import java.io.File
import java.io.FileOutputStream
import java.io.IOException
import java.io.InputStreamReader
import java.io.OutputStreamWriter
import java.io.RandomAccessFile
import java.net.URL
import java.security.MessageDigest
import java.util.Base64
import java.util.concurrent.CompletableFuture
import java.util.concurrent.TimeUnit
import java.util.concurrent.atomic.AtomicLong
import java.util.zip.GZIPInputStream
import kotlin.math.roundToInt

/**
 * Protocol 39: Vessel owns UML, VirtIO GPU, VirtIO input and presentation in
 * one Android UID. Input is Android -> native sender -> vhost-user
 * virtio-input -> Linux evdev/libinput. There is no guest TCP/uinput bridge,
 * VNC, RGB frame transport, Termux dependency or software-render fallback.
 */
class VesselRuntimeController(
    private val context: Context,
    private val progress: (String, Int, String) -> Unit,
) {
    companion object {
        const val PROTOCOL = 40
        const val REVISION = "v60-private-rootfs-fast-storage-r1"
        const val DISPLAY_TRANSPORT = "vhost-user-gpu-ahb-pageflip-ring-v7"
        const val INPUT_TRANSPORT = "virtio-input-vhost-user-same-uid-v1"
        const val UML_VCPUS = 6
        private const val ROOTFS_URL = "https://github.com/zalexdev/linux-um-arm64/releases/download/prebuilt-20260816/debian-docker.ext4.gz"
        private const val ROOTFS_SHA256 = "2807979f76021fadf1f76f0c827fbe1eab4df51e33bfeca0c840c5181c610be3"
        private const val GUEST_READY_BANNER = "Type 'exit' to shut the kernel down and return to Android."
        private const val VIRTIO_GPU_ID = 16
        private const val VIRTIO_INPUT_ID = 18
        private const val MIN_DISK_CAPACITY_BYTES = 10L * 1024L * 1024L * 1024L
        private const val MIN_HOST_FREE_BYTES = 2L * 1024L * 1024L * 1024L
        private const val MIN_GUEST_FREE_KIB = 512_000L
        private const val PREFERRED_GUEST_FREE_KIB = 2_000_000L
    }

    private data class InputBackendSpec(
        val label: String,
        val device: String,
        val vhostSocket: File,
        val controlSocket: File,
    )

    private val runtimeDir = File(context.filesDir, "vessel-runtime").apply { mkdirs() }
    private val gpuSocket = File(runtimeDir, "vessel-vugpu.sock")
    val displaySocket = File(runtimeDir, "vessel-vugpu.sock.display")
    private val touchVhostSocket = File(runtimeDir, "vessel-input-touch.sock")
    private val pointerVhostSocket = File(runtimeDir, "vessel-input-pointer.sock")
    private val keyboardVhostSocket = File(runtimeDir, "vessel-input-keyboard.sock")
    private val touchControlSocket = File(runtimeDir, "vessel-input-touch.ctl")
    private val pointerControlSocket = File(runtimeDir, "vessel-input-pointer.ctl")
    private val keyboardControlSocket = File(runtimeDir, "vessel-input-keyboard.ctl")
    private val nativeDir = File(context.applicationInfo.nativeLibraryDir)

    private val legacyMachineDir: File = File(
        Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS),
        "LinuxPC/Vessel-Debian",
    )
    // The live ext4 image belongs on Android's real private filesystem.
    // /storage/emulated/0 is an emulated/FUSE-style path and is far slower
    // for the random 4 KiB I/O generated by a desktop Linux filesystem.
    val machineDir: File = File(context.filesDir, "vessel-machine").apply { mkdirs() }
    private val disk = File(machineDir, "debian-docker.ext4")
    private val persistentLog = File(machineDir, "vessel-runtime.log")

    val guestMemoryMb: Int by lazy {
        val info = ActivityManager.MemoryInfo()
        context.getSystemService(ActivityManager::class.java)?.getMemoryInfo(info)
        val totalMb = (info.totalMem / (1024L * 1024L)).toInt().coerceAtLeast(4096)
        val automatic = ((totalMb * 3) / 10).coerceIn(2048, 4096)
        VesselExperimentConfig.memoryMb(context).takeIf { it > 0 } ?: automatic
    }

    val selectedVcpus: Int
        get() = VesselExperimentConfig.vcpus(context)

    private val umlBin get() = File(nativeDir, "libvessel_uml.so")
    private val stubBin get() = File(nativeDir, "libvessel_stub.so")
    private val umnetBin get() = File(nativeDir, "libvessel_umnet.so")
    private val passtBin get() = File(nativeDir, "libvessel_passt.so")
    private val gpuSystemBin get() = File(nativeDir, "libvessel_vhost_gpu_system.so")
    private val gpuAngleBin get() = File(nativeDir, "libvessel_vhost_gpu_angle.so")
    private val gpuBin get() = if (VesselExperimentConfig.hostGl(context) == "angle") gpuAngleBin else gpuSystemBin
    private val bridgeSystem get() = File(nativeDir, "libvessel_ahb_bridge_system.so")
    private val bridgeAngle get() = File(nativeDir, "libvessel_ahb_bridge_angle.so")
    private val inputBin get() = File(nativeDir, "libvessel_vhost_input.so")
    private val virglLib get() = File(nativeDir, "libvessel_virglrenderer.so")
    private val epoxyLib get() = File(nativeDir, "libvessel_epoxy.so")
    private val eglAngle get() = File(nativeDir, "libEGL_angle.so")
    private val glesAngle get() = File(nativeDir, "libGLESv2_angle.so")
    private val angleSelector get() = File(nativeDir, "libvessel_angle_select.so")

    private val inputSpecs: List<InputBackendSpec>
        get() = listOf(
            InputBackendSpec("touch", "touch", touchVhostSocket, touchControlSocket),
            InputBackendSpec("pointer", "pointer", pointerVhostSocket, pointerControlSocket),
            InputBackendSpec("keyboard", "keyboard", keyboardVhostSocket, keyboardControlSocket),
        )

    @Volatile private var displayWidth = 1280
    @Volatile private var displayHeight = 720
    @Volatile private var displayDpi = 120
    @Volatile private var displayRefresh = 120f

    @Volatile private var gpuProcess: Process? = null
    @Volatile private var umlProcess: Process? = null
    @Volatile private var inputProcesses: List<Process> = emptyList()
    @Volatile private var running = false
    @Volatile private var stopping = false
    @Volatile private var guestReady = false
    @Volatile private var inputReady = false
    @Volatile private var desktopReady = false
    @Volatile private var lastError = ""
    @Volatile private var startedAt = 0L
    @Volatile private var lastInputFailure = ""

    private val logLock = Any()
    private val log = StringBuilder()
    private val commandLock = Any()
    private val consoleLock = Any()
    @Volatile private var consoleWriter: BufferedWriter? = null
    @Volatile private var pendingMarker: String? = null
    @Volatile private var pendingFuture: CompletableFuture<Pair<Int, String>>? = null
    @Volatile private var pendingLineObserver: ((String) -> Unit)? = null
    private val pendingOutput = StringBuilder()
    private val commandId = AtomicLong()
    @Volatile private var guestShellReady = CompletableFuture<Unit>()
    @Volatile private var useGuestAgent = false

    fun hasStorageAccess(): Boolean = machineDir.isDirectory || machineDir.mkdirs()

    private fun runtimeFiles(): List<File> = listOf(
        umlBin, stubBin, umnetBin, passtBin, gpuSystemBin, gpuAngleBin, inputBin,
        bridgeSystem, bridgeAngle, virglLib, epoxyLib, eglAngle, glesAngle, angleSelector,
    )

    fun hostAssetsReady(): Boolean = runtimeFiles().all { it.isFile && it.length() > 0L }

    private fun normalizeWidth(value: Int) = ((value.coerceIn(640, 3840) / 8) * 8).coerceAtLeast(640)
    private fun normalizeHeight(value: Int) = ((value.coerceIn(480, 2160) / 2) * 2).coerceAtLeast(480)

    fun configureDisplay(width: Int, height: Int, dpi: Int, refresh: Float) {
        displayWidth = normalizeWidth(width)
        displayHeight = normalizeHeight(height)
        displayDpi = dpi.coerceIn(72, 480)
        displayRefresh = refresh.coerceIn(30f, 240f)
        VesselWaylandPresenter.configure(
            displaySocket.absolutePath,
            displayWidth,
            displayHeight,
            displayDpi,
            displayRefresh,
        )
    }

    suspend fun resizeDesktop(width: Int, height: Int, dpi: Int, refresh: Float): Boolean = withContext(Dispatchers.IO) {
        configureDisplay(width, height, dpi, refresh)
        if (!running || !guestReady) return@withContext true
        runCatching { applyDisplayModeBlocking() }.getOrElse {
            append("[display] resize failed: ${it.message}\n")
            false
        }
    }

    private fun append(text: String) {
        synchronized(logLock) {
            log.append(text)
            if (log.length > 300_000) log.delete(0, log.length - 240_000)
            if (machineDir.isDirectory) {
                runCatching {
                    FileOutputStream(persistentLog, true).bufferedWriter().use { it.write(text) }
                    if (persistentLog.length() > 2_000_000L) {
                        persistentLog.writeText(persistentLog.readText().takeLast(1_000_000))
                    }
                }
            }
        }
    }

    private fun logTail(): String = synchronized(logLock) { log.takeLast(180_000).toString() }
    private fun inputBackendsAlive(): Boolean = inputProcesses.size == inputSpecs.size && inputProcesses.all { it.isAlive }
    private fun presenterVisible(status: String): Boolean =
        status.startsWith("presenting-native-surface") || status.startsWith("presenting-retained")

    private fun baseState(ok: Boolean = true): JSONObject = JSONObject()
        .put("ok", ok)
        .put("protocolVersion", PROTOCOL)
        .put("runtimeRevision", REVISION)
        .put("hotRuntimeRevision", VesselUpdateManager.currentRuntimeRevision(context))
        .put("displayTransport", DISPLAY_TRANSPORT)
        .put("inputTransport", INPUT_TRANSPORT)
        .put("backend", "UML_VIRTIO_GPU_VIRTIO_INPUT_NATIVE")
        .put("renderer", "KDE Plasma/${if (VesselExperimentConfig.desktopBackend(context) == "wayland") "Wayland" else "X11"} -> Mesa VirGL -> virglrenderer -> ${VesselExperimentConfig.hostGl(context)} EGL -> async AHB -> SurfaceFlinger")
        .put("rendererMode", "virgl-opengl")
        .put("translationLayer", "VirGL")
        .put("gpuOnly", true)
        .put("softwareFallback", false)
        .put("vncPort", -1)
        .put("runtimeDir", runtimeDir.absolutePath)
        .put("machineDir", machineDir.absolutePath)
        .put("guestMemoryMb", guestMemoryMb)
        .put("vcpus", selectedVcpus)
        .put("running", running)
        .put("guestReady", guestReady)
        .put("desktopReady", desktopReady)
        .put("frameContentValidated", presenterVisible(VesselWaylandPresenter.status()))
        .put("inputConnected", inputReady && inputBackendsAlive())
        .put("inputSender", VesselVirtioInput.status())
        .put("controlTransport", if (useGuestAgent) VesselGuestAgent.status() else "boot-tty")
        .put("audioTransport", VesselAudioBridge.status())
        .put("displayWidth", displayWidth)
        .put("displayHeight", displayHeight)
        .put("displayDpi", displayDpi)
        .put("displayRefresh", displayRefresh.toDouble())
        .put("uptimeMs", if (running) android.os.SystemClock.elapsedRealtime() - startedAt else 0L)
        .put("logTail", logTail())
        .put("lastError", lastError)

    suspend fun status(): JSONObject = withContext(Dispatchers.IO) {
        val presenter = VesselWaylandPresenter.status()
        if (presenterVisible(presenter)) {
            desktopReady = true
            lastError = ""
        }
        if (inputReady && !inputBackendsAlive()) inputReady = false
        baseState().put("presenter", presenter)
    }

    private fun assertAssets() {
        val missing = runtimeFiles().filterNot { it.isFile && it.length() > 0L }
        check(missing.isEmpty()) { "Vessel APK is missing native runtime assets: ${missing.joinToString { it.name }}" }
    }

    private fun sha256(file: File): String {
        val digest = MessageDigest.getInstance("SHA-256")
        file.inputStream().buffered(256 * 1024).use { input ->
            val b = ByteArray(256 * 1024)
            while (true) {
                val n = input.read(b)
                if (n < 0) break
                digest.update(b, 0, n)
            }
        }
        return digest.digest().joinToString("") { "%02x".format(it) }
    }

    private fun ensureDiskBackingCapacity() {
        if (disk.length() >= MIN_DISK_CAPACITY_BYTES) return
        val hostFree = machineDir.usableSpace
        if (hostFree > 0L) {
            check(hostFree >= MIN_HOST_FREE_BYTES) {
                "Vessel needs at least 2 GiB of free Android storage to finish the Debian desktop setup"
            }
        }
        val before = disk.length()
        progress("disk_capacity", 26, "Growing Debian disk capacity safely")
        RandomAccessFile(disk, "rw").use { it.setLength(MIN_DISK_CAPACITY_BYTES) }
        check(disk.length() == MIN_DISK_CAPACITY_BYTES) { "Could not expand Debian disk backing file" }
        append(
            "[disk] sparse backing capacity ${before / (1024 * 1024)} MiB -> " +
                "${MIN_DISK_CAPACITY_BYTES / (1024 * 1024)} MiB; physical storage grows only as Linux writes data\n",
        )
    }

    private fun migrateLegacyDiskIfNeeded() {
        if (disk.isFile && disk.length() > 512L * 1024 * 1024) return
        val legacyDisk = File(legacyMachineDir, "debian-docker.ext4")
        if (!legacyDisk.isFile || legacyDisk.length() <= 512L * 1024 * 1024 || !legacyDisk.canRead()) return

        val tmp = File(machineDir, "debian-docker.ext4.migrating")
        tmp.delete()
        val total = legacyDisk.length().coerceAtLeast(1L)
        progress("disk_migrate", 5, "Moving Linux disk to fast private storage once")
        val buffer = ByteArray(1024 * 1024)
        try {
            RandomAccessFile(legacyDisk, "r").use { src ->
                RandomAccessFile(tmp, "rw").use { dst ->
                    dst.setLength(0L)
                    var done = 0L
                    while (true) {
                        val n = src.read(buffer)
                        if (n < 0) break
                        var nonZero = false
                        var i = 0
                        while (i < n) {
                            if (buffer[i].toInt() != 0) {
                                nonZero = true
                                break
                            }
                            i++
                        }
                        if (nonZero) dst.write(buffer, 0, n) else dst.seek(dst.filePointer + n)
                        done += n
                        if (done % (64L * 1024 * 1024) < buffer.size) {
                            val pct = (5 + (done * 18L / total).toInt()).coerceIn(5, 23)
                            progress("disk_migrate", pct, "Migrating Linux disk to fast private storage")
                        }
                    }
                    dst.setLength(src.length())
                }
            }
            if (disk.exists()) check(disk.delete()) { "Cannot replace incomplete private Debian disk" }
            check(tmp.renameTo(disk)) { "Could not finish private Debian disk migration" }
            append("[storage] sparse-migrated legacy rootfs to ${disk.absolutePath}; legacy copy retained for safety\n")
        } catch (t: Throwable) {
            tmp.delete()
            throw IllegalStateException("Could not migrate the existing Debian disk to fast private storage", t)
        }
    }

    private fun ensureDisk() {
        check(machineDir.exists() || machineDir.mkdirs()) { "Cannot create ${machineDir.absolutePath}" }
        migrateLegacyDiskIfNeeded()
        if (!disk.isFile || disk.length() <= 512L * 1024 * 1024) {
            val gz = File(machineDir, "debian-docker.ext4.gz.part")
            val tmp = File(machineDir, "debian-docker.ext4.part")
            gz.delete(); tmp.delete()
            progress("disk_download", 4, "Downloading Debian once to fast private storage")
            val connection = URL(ROOTFS_URL).openConnection().apply {
                connectTimeout = 20_000
                readTimeout = 60_000
                setRequestProperty("User-Agent", "Vessel/2.1")
            }
            connection.getInputStream().buffered(256 * 1024).use { input ->
                FileOutputStream(gz).buffered(256 * 1024).use { out ->
                    val b = ByteArray(256 * 1024)
                    var done = 0L
                    while (true) {
                        val n = input.read(b)
                        if (n < 0) break
                        out.write(b, 0, n)
                        done += n
                        progress("disk_download", (4 + (done / 4_000_000L).toInt()).coerceAtMost(24), "Downloading persistent Debian image")
                    }
                }
            }
            check(sha256(gz) == ROOTFS_SHA256) { "Debian image checksum mismatch" }
            progress("disk_extract", 25, "Preparing persistent Debian disk")
            GZIPInputStream(gz.inputStream().buffered(256 * 1024), 256 * 1024).use { input ->
                FileOutputStream(tmp).buffered(256 * 1024).use { out -> input.copyTo(out, 256 * 1024) }
            }
            check(tmp.length() > 512L * 1024 * 1024) { "Debian disk extraction failed" }
            if (disk.exists()) check(disk.delete()) { "Cannot replace incomplete Debian disk" }
            check(tmp.renameTo(disk)) { "Could not promote persistent Debian disk" }
            gz.delete()
        }
        ensureDiskBackingCapacity()
    }

    private fun startProcessLogReader(process: Process, threadName: String, prefix: String) {
        Thread({
            try {
                process.inputStream.bufferedReader().useLines { lines ->
                    lines.forEach { append("$prefix$it\n") }
                }
            } catch (t: Throwable) {
                if (!stopping && process.isAlive) append("$prefix[log reader closed: ${t.message}]\n")
            }
        }, threadName).apply { isDaemon = true; start() }
    }

    private fun stopInputBackends() {
        inputProcesses.forEach { p -> runCatching { if (p.isAlive) p.destroyForcibly() } }
        inputProcesses = emptyList()
        inputReady = false
        inputSpecs.forEach { spec ->
            spec.vhostSocket.delete()
            spec.controlSocket.delete()
        }
    }


    private val staleRuntimeNeedles = listOf(
        "libvessel_uml.so",
        "libvessel_umnet.so",
        "libvessel_passt.so",
        "libvessel_vhost_gpu.so",
        "libvessel_vhost_gpu_system.so",
        "libvessel_vhost_gpu_angle.so",
        "libvessel_vhost_input.so",
    )

    private fun killStaleNativeRuntimeProcesses(reason: String) {
        val myUid = android.os.Process.myUid()
        val myPid = android.os.Process.myPid()
        var killed = 0
        File("/proc").listFiles().orEmpty().forEach { dir ->
            val pid = dir.name.toIntOrNull() ?: return@forEach
            if (pid == myPid) return@forEach
            val uid = runCatching {
                File(dir, "status").useLines { lines ->
                    lines.firstOrNull { it.startsWith("Uid:") }
                        ?.substringAfter("Uid:")?.trim()?.split(Regex("\\s+"))?.firstOrNull()?.toIntOrNull()
                }
            }.getOrNull()
            if (uid != myUid) return@forEach
            val command = runCatching {
                File(dir, "cmdline").readBytes().toString(Charsets.UTF_8).replace('\u0000', ' ')
            }.getOrDefault("")
            if (staleRuntimeNeedles.none { command.contains(it) }) return@forEach
            runCatching {
                Os.kill(pid, OsConstants.SIGKILL)
                killed++
                append("[host] killed stale Vessel native pid=$pid reason=$reason cmd=${command.take(180)}\\n")
            }
        }
        if (killed > 0) Thread.sleep(120)
    }

    private fun startInputBackends() {
        stopInputBackends()
        val started = mutableListOf<Process>()
        try {
            inputSpecs.forEach { spec ->
                spec.vhostSocket.delete()
                spec.controlSocket.delete()
                append("[input] starting ${spec.label} virtio-input backend\n")
                val pb = ProcessBuilder(
                    inputBin.absolutePath,
                    "--socket-path", spec.vhostSocket.absolutePath,
                    "--control-path", spec.controlSocket.absolutePath,
                    "--device", spec.device,
                ).redirectErrorStream(true)
                pb.environment()["RUST_LOG"] = "info"
                val p = pb.start()
                started += p
                startProcessLogReader(p, "vessel-input-${spec.label}-log", "[input-${spec.label}] ")

                var tries = 0
                while ((!spec.vhostSocket.exists() || !spec.controlSocket.exists()) && tries++ < 150) {
                    if (!p.isAlive) error("${spec.label} virtio-input backend exited rc=${runCatching { p.exitValue() }.getOrDefault(-1)}")
                    Thread.sleep(20)
                }
                check(spec.vhostSocket.exists() && spec.controlSocket.exists()) {
                    "${spec.label} virtio-input sockets did not become ready"
                }
            }
            inputProcesses = started.toList()
            VesselVirtioInput.configure(
                touchControlSocket.absolutePath,
                pointerControlSocket.absolutePath,
                keyboardControlSocket.absolutePath,
            )
            append("[input] native virtio-input backends ready\n")
        } catch (t: Throwable) {
            started.forEach { p -> runCatching { if (p.isAlive) p.destroyForcibly() } }
            stopInputBackends()
            throw t
        }
    }

    fun input(type: String, values: Map<String, Any>) {
        if (!running || !inputReady) return
        if (!VesselVirtioInput.send(type, values)) {
            inputReady = false
            val status = VesselVirtioInput.status()
            if (status != lastInputFailure) {
                lastInputFailure = status
                append("[input] native virtio-input send failed: $status\n")
            }
        }
    }

    private fun startGpu() {
        runCatching { gpuProcess?.destroyForcibly() }
        gpuSocket.delete()
        var presenterReady = displaySocket.exists()
        var tries = 0
        while (!presenterReady && tries++ < 100) {
            Thread.sleep(20)
            presenterReady = displaySocket.exists()
        }
        check(presenterReady) { "Native vhost-user-gpu display socket did not start: ${VesselWaylandPresenter.status()}" }
        val hostGl = VesselExperimentConfig.hostGl(context)
        append("[host] starting vhost-device-gpu; display=${displaySocket.absolutePath} hostGl=$hostGl\n")
        val pb = ProcessBuilder(
            gpuBin.absolutePath,
            "--socket-path", gpuSocket.absolutePath,
            "--gpu-mode", "virglrenderer",
            "--capset", "virgl,virgl2",
            "--use-egl", "true",
            "--use-glx", "false",
            "--use-gles", "true",
            "--use-surfaceless", "true",
        ).redirectErrorStream(true)
        pb.environment()["LD_LIBRARY_PATH"] = nativeDir.absolutePath
        if (hostGl == "angle") {
            pb.environment()["LD_PRELOAD"] = angleSelector.absolutePath
            pb.environment()["VESSEL_ANGLE_PATH"] = nativeDir.absolutePath
            pb.environment()["EPOXY_USE_ANGLE"] = "1"
        } else {
            pb.environment().remove("LD_PRELOAD")
            pb.environment().remove("VESSEL_ANGLE_PATH")
            pb.environment().remove("EPOXY_USE_ANGLE")
        }
        pb.environment()["VESSEL_HOST_GL"] = hostGl
        pb.environment()["RUST_LOG"] = "info"
        pb.environment()["VESSEL_FLIP_Y"] = if (VesselExperimentConfig.flipDisplayY(context)) "1" else "0"
        val p = pb.start()
        gpuProcess = p
        startProcessLogReader(p, "vessel-gpu-log", "[gpu] ")
        tries = 0
        while (!gpuSocket.exists() && tries++ < 150) {
            if (!p.isAlive) error("vhost-device-gpu exited during startup rc=${runCatching { p.exitValue() }.getOrDefault(-1)}")
            Thread.sleep(40)
        }
        check(gpuSocket.exists()) { "vhost-device-gpu socket did not appear" }
        append("[host] vhost-device-gpu ready\n")
    }

    private fun startUml() {
        runCatching { umlProcess?.destroyForcibly() }
        guestShellReady = CompletableFuture()
        append("[host] starting UML with ${guestMemoryMb} MiB RAM, $selectedVcpus vCPUs\n")
        val cmd = listOf(
            umnetBin.absolutePath, "--passt", passtBin.absolutePath, "--dns", "1.1.1.1", "--",
            umlBin.absolutePath,
            "mem=${guestMemoryMb}M", "ncpus=$selectedVcpus", "seccomp=on",
            "ubd0=${disk.absolutePath}", "root=/dev/ubda", "rw", "init=/umarm-init",
            "stub_exe=${stubBin.absolutePath}",
            "virtio_uml.device=${gpuSocket.absolutePath}:$VIRTIO_GPU_ID",
            "virtio_uml.device=${touchVhostSocket.absolutePath}:$VIRTIO_INPUT_ID",
            "virtio_uml.device=${pointerVhostSocket.absolutePath}:$VIRTIO_INPUT_ID",
            "virtio_uml.device=${keyboardVhostSocket.absolutePath}:$VIRTIO_INPUT_ID",
            "panic=-1", "con=null", "con0=fd:0,fd:1", "console=tty0",
        )
        val p = ProcessBuilder(cmd).directory(machineDir).redirectErrorStream(true).start()
        umlProcess = p
        append("[host] UML launcher started\n")
        consoleWriter = BufferedWriter(OutputStreamWriter(p.outputStream, Charsets.UTF_8), 32 * 1024)
        Thread({
            try {
                BufferedReader(InputStreamReader(p.inputStream, Charsets.UTF_8), 64 * 1024).use { reader ->
                    while (true) {
                        val line = reader.readLine() ?: break
                        append("$line\n")
                        if (line.contains(GUEST_READY_BANNER) && guestShellReady.complete(Unit)) {
                            append("[guest] interactive shell ready\n")
                        }
                        var observer: ((String) -> Unit)? = null
                        synchronized(consoleLock) {
                            val marker = pendingMarker
                            val markerToken = marker?.let { "$it:" }
                            val markerAt = markerToken?.let { line.indexOf(it) } ?: -1
                            if (marker != null && markerToken != null && markerAt >= 0) {
                                val suffix = line.substring(markerAt + markerToken.length)
                                val rc = Regex("""^-?\d+""").find(suffix)?.value?.toIntOrNull()
                                if (rc != null) {
                                    pendingFuture?.complete(rc to pendingOutput.toString())
                                    pendingMarker = null
                                    pendingFuture = null
                                    pendingLineObserver = null
                                    pendingOutput.setLength(0)
                                } else {
                                    pendingOutput.append(line).append('\n')
                                    observer = pendingLineObserver
                                }
                            } else if (marker != null) {
                                pendingOutput.append(line).append('\n')
                                observer = pendingLineObserver
                            }
                        }
                        observer?.let { runCatching { it(line) } }
                    }
                }
            } catch (t: Throwable) {
                if (!stopping) append("[host] UML console reader closed unexpectedly: ${t.message}\n")
            } finally {
                val rc = runCatching { p.waitFor() }.getOrDefault(-1)
                val failure = IllegalStateException("UML exited before guest command completed (rc=$rc)")
                synchronized(consoleLock) {
                    pendingFuture?.completeExceptionally(failure)
                    pendingFuture = null
                    pendingMarker = null
                    pendingLineObserver = null
                    pendingOutput.setLength(0)
                }
                if (!stopping) {
                    guestShellReady.completeExceptionally(IllegalStateException("UML exited before guest shell was ready (rc=$rc)"))
                }
                if (!stopping) {
                    val memory = ActivityManager.MemoryInfo()
                    context.getSystemService(ActivityManager::class.java)?.getMemoryInfo(memory)
                    val signalHint = if (rc == 137) "SIGKILL/137" else "exit=$rc"
                    append("[crash] UML $signalHint; hostAvailMiB=${memory.availMem / (1024 * 1024)} lowMemory=${memory.lowMemory} thresholdMiB=${memory.threshold / (1024 * 1024)} control=${VesselGuestAgent.status()} audio=${VesselAudioBridge.status()}\n")
                }
                append("[host] UML launcher exited rc=$rc\n")
                running = false
                guestReady = false
                inputReady = false
                desktopReady = false
            }
        }, "vessel-uml-console").apply { isDaemon = true; start() }
    }

    private fun awaitGuestShell(timeoutSeconds: Int) {
        check(umlProcess?.isAlive == true) { "UML is not running" }
        try {
            guestShellReady.get(timeoutSeconds.toLong(), TimeUnit.SECONDS)
        } catch (t: Throwable) {
            throw IllegalStateException("Debian userspace did not reach the interactive shell within ${timeoutSeconds}s", t)
        }
    }

    private fun guestBlocking(
        command: String,
        timeoutSeconds: Int,
        onLine: ((String) -> Unit)? = null,
    ): Pair<Int, String> = synchronized(commandLock) {
        if (useGuestAgent) {
            return@synchronized try {
                VesselGuestAgent.execute(command, timeoutSeconds, onLine)
            } catch (t: Throwable) {
                append("[control] guest-agent command failed: ${t.message}\n")
                throw t
            }
        }
        val future: CompletableFuture<Pair<Int, String>>
        synchronized(consoleLock) {
            check(umlProcess?.isAlive == true) { "UML is not running" }
            check(pendingFuture == null) { "Another guest command is running" }
            val marker = "__VESSEL_${commandId.incrementAndGet()}__"
            future = CompletableFuture()
            pendingMarker = marker
            pendingFuture = future
            pendingLineObserver = onLine
            pendingOutput.setLength(0)
            val encoded = Base64.getEncoder().encodeToString(command.toByteArray(Charsets.UTF_8))
            consoleWriter!!.apply {
                // Feed arbitrary user commands to a fresh bash process instead of
                // pasting them directly into the interactive root shell. This
                // preserves quotes, pipes, semicolons and multiline commands.
                write("printf '%s' '$encoded' | base64 -d | /bin/bash; __vessel_rc=\$?; printf '\\n$marker:%s\\n' \"\$__vessel_rc\"\n")
                flush()
            }
        }
        try {
            future.get(timeoutSeconds.toLong(), TimeUnit.SECONDS)
        } catch (t: java.util.concurrent.TimeoutException) {
            val buffered = synchronized(consoleLock) {
                if (pendingFuture === future) pendingOutput.takeLast(8000) else ""
            }
            append("[guest] command timeout after ${timeoutSeconds}s: ${command.lineSequence().firstOrNull()?.take(240) ?: "<empty>"}\n")
            if (buffered.isNotBlank()) append("[guest] pending console output before timeout:\n$buffered\n")
            throw IllegalStateException("Guest command timed out after ${timeoutSeconds}s", t)
        } finally {
            if (!future.isDone) synchronized(consoleLock) {
                if (pendingFuture === future) {
                    pendingMarker = null
                    pendingFuture = null
                    pendingLineObserver = null
                    pendingOutput.setLength(0)
                }
            }
        }
    }


    private fun ensureGuestNetworkBlocking() {
        val command = """
            set +e
            iface=${'$'}(ip -o link show 2>/dev/null | awk -F': ' '${'$'}2 == "vec0" {print ${'$'}2; exit}')
            [ -n "${'$'}iface" ] || iface=${'$'}(ip -o link show 2>/dev/null | awk -F': ' '${'$'}2 ~ /^vec/ {print ${'$'}2; exit}')
            if [ -z "${'$'}iface" ]; then echo VESSEL_NET_FAIL=no-vector-interface; exit 21; fi
            ip link set "${'$'}iface" up || true
            ip addr replace 10.0.2.15/24 dev "${'$'}iface" || { echo VESSEL_NET_FAIL=address; exit 22; }
            ip route replace default via 10.0.2.2 dev "${'$'}iface" || { echo VESSEL_NET_FAIL=route; exit 23; }
            cat >/etc/resolv.conf <<'VESSEL_RESOLV'
            nameserver 1.1.1.1
            nameserver 8.8.8.8
            options timeout:2 attempts:2
            VESSEL_RESOLV
            getent ahosts deb.debian.org >/tmp/vessel-net-dns.txt 2>&1 || { echo VESSEL_NET_FAIL=dns; cat /tmp/vessel-net-dns.txt; exit 24; }
            timeout 7 /bin/bash -lc 'exec 3<>/dev/tcp/deb.debian.org/443' >/tmp/vessel-net-tcp.txt 2>&1 || { echo VESSEL_NET_FAIL=tcp443; cat /tmp/vessel-net-tcp.txt; exit 25; }
            echo VESSEL_NETWORK_READY iface=${'$'}iface route=${'$'}(ip route show default | head -1)
        """.trimIndent()
        val result = guestBlocking(command, 30)
        if (result.first == 0) append("[network] ${result.second.lineSequence().lastOrNull { it.contains("VESSEL_NETWORK_READY") } ?: "external connectivity ready"}\\n")
        else append("[network] external connectivity probe failed rc=${result.first}: ${result.second.takeLast(3000)}\\n")
    }

    private fun ensureGuestFilesystemCapacity() {
        progress("disk_resize", 43, "Expanding Debian filesystem")
        val (rc, out) = guestBlocking(
            "if command -v resize2fs >/dev/null 2>&1; then resize2fs /dev/ubda; else echo 'resize2fs is missing from the Debian base image'; false; fi",
            180,
        )
        if (rc != 0) {
            append("[disk] resize2fs failed rc=$rc ${out.takeLast(3000)}\n")
            error("Could not expand the Debian ext4 filesystem to its backing disk capacity")
        }
        val (freeRc, freeOut) = guestBlocking(
            "avail=\$(df -Pk / | awk 'NR==2 {print \$4}'); echo free_kib=\$avail; test \$avail -ge $MIN_GUEST_FREE_KIB",
            15,
        )
        check(freeRc == 0) {
            "Debian filesystem is critically low on free space after resize (${freeOut.trim()}); Vessel requires at least ${MIN_GUEST_FREE_KIB} KiB free"
        }
        val freeKib = Regex("""free_kib=(\d+)""").find(freeOut)?.groupValues?.getOrNull(1)?.toLongOrNull()
        if (freeKib != null && freeKib < PREFERRED_GUEST_FREE_KIB) {
            append("[disk] warning: ${freeOut.trim()} after ext4 resize; below preferred ${PREFERRED_GUEST_FREE_KIB} KiB but safe to boot\n")
        } else {
            append("[disk] ${freeOut.trim()} after ext4 resize\n")
        }
    }

    private fun awaitVirtioInputDevices() {
        check(inputBackendsAlive()) { "VirtIO input backend process exited before guest enumeration" }
        var ready = false
        var last = ""
        var tries = 0
        while (!ready && tries++ < 100) {
            val result = guestBlocking(
                "test -r /proc/bus/input/devices && " +
                    "grep -Fq 'Vessel Touchscreen' /proc/bus/input/devices && " +
                    "grep -Fq 'Vessel Trackpad' /proc/bus/input/devices && " +
                    "grep -Fq 'Vessel Keyboard' /proc/bus/input/devices",
                5,
            )
            ready = result.first == 0
            last = result.second
            if (!ready) Thread.sleep(100)
        }
        check(ready) { "Linux virtio-input devices did not appear: ${last.takeLast(3000)}" }
        check(VesselVirtioInput.send("rel", mapOf("dx" to 0, "dy" to 0))) {
            "Android -> virtio-input control path failed: ${VesselVirtioInput.status()}"
        }
        check(inputBackendsAlive()) { "VirtIO input backend exited during input validation" }
        inputReady = true
        lastInputFailure = ""
        append("[input] Linux evdev devices ready; sender=${VesselVirtioInput.status()}\n")
    }

    private fun plasmaReadyCommand(): String =
        "missing=''; " +
            "for c in kwin_wayland startplasma-wayland Xwayland startplasma-x11 Xorg xrandr xinput systemsettings konsole firefox-esr; do command -v \"\$c\" >/dev/null 2>&1 || missing=\"\$missing cmd:\$c\"; done; " +
            "for p in kwin-wayland plasma-workspace-wayland xwayland qtwayland5 python3-dbus python3-gi qml-module-org-kde-qqc2desktopstyle qml-module-org-kde-kirigami2 qml-module-org-kde-kitemmodels qml-module-org-kde-kquickcontrolsaddons qml-module-qtquick-controls qml-module-qtquick-controls2 qml-module-qtquick-layouts qml-module-qtquick-window2 qml-module-qtquick2 qml-module-qtquick-templates2 qml-module-qtgraphicaleffects qml-module-qt-labs-platform plasma-integration plasma-pa pulseaudio pulseaudio-utils alsa-utils kactivitymanagerd libkf5service-data fonts-noto-color-emoji packagekit packagekit-tools policykit-1 plasma-discover apt-config-icons apt-config-icons-large apt-config-icons-hidpi librsvg2-bin; do " +
            "dpkg-query -W -f='\${Status}' \"\$p\" 2>/dev/null | grep -q 'install ok installed' || missing=\"\$missing pkg:\$p\"; done; " +
            "qml=/usr/lib/aarch64-linux-gnu/qt5/qml; test -d /usr/share/icons/breeze || missing=\"\$missing path:breeze\"; " +
            "test -f /etc/xdg/menus/kf5-applications.menu || missing=\"\$missing path:kf5-menu\"; " +
            "test -e /usr/lib/aarch64-linux-gnu/dri/virtio_gpu_dri.so || missing=\"\$missing path:virtio_gpu_dri.so\"; " +
            "test -f \"\$qml/QtQuick/Templates.2/qmldir\" || missing=\"\$missing qml:Templates.2\"; " +
            "test -f \"\$qml/QtGraphicalEffects/qmldir\" || missing=\"\$missing qml:GraphicalEffects\"; " +
            "test -f \"\$qml/org/kde/kirigami.2/qmldir\" || missing=\"\$missing qml:kirigami\"; " +
            "test -z \"\$missing\" || { echo VESSEL_MISSING_COMPONENTS=\"\$missing\"; exit 1; }"

    private fun packagePolicyCommand(): String = """
        install -d -m 755 /usr/sbin
        cat >/usr/sbin/policy-rc.d <<'VESSEL_POLICY'
        #!/bin/sh
        # Vessel UML uses a custom PID 1. Package maintainer scripts must not
        # auto-start system services while the persistent image is provisioned.
        exit 101
        VESSEL_POLICY
        chmod 0755 /usr/sbin/policy-rc.d
        install -d -m 755 /etc/initramfs-tools
        cat >/etc/initramfs-tools/update-initramfs.conf <<'VESSEL_INITRAMFS'
        # Vessel boots the host-provided UML kernel directly; generating a guest
        # initramfs is both useless and can stall package triggers for minutes.
        update_initramfs=no
        backup_initramfs=no
        VESSEL_INITRAMFS
    """.trimIndent()

    private inner class PackageProgressReporter(
        private val stage: String,
        private val startPercent: Int,
    ) {
        private var total = 0
        private var downloaded = 0
        private var unpacked = 0
        private var configured = 0
        private var lastPercent = startPercent

        private fun emit(percent: Int, detail: String) {
            val next = percent.coerceIn(lastPercent, 71)
            lastPercent = next
            progress(stage, next, detail)
        }

        fun onLine(raw: String) {
            val line = raw
                .replace("\u001B[?2004h", "")
                .replace("\u001B[?2004l", "")
                .trim()
            if (line.isBlank()) return

            Regex("""(\d+) newly installed""").find(line)?.groupValues?.getOrNull(1)?.toIntOrNull()?.let {
                if (it > 0) total = it
            }
            Regex("""VESSEL_PENDING_PACKAGES=(\d+)""").find(line)?.groupValues?.getOrNull(1)?.toIntOrNull()?.let {
                if (it > 0) total = it
            }

            Regex("""^Get:(\d+)\s""").find(line)?.groupValues?.getOrNull(1)?.toIntOrNull()?.let { index ->
                downloaded = maxOf(downloaded, index)
                val pct = if (total > 0) 56 + (downloaded.coerceAtMost(total) * 6 / total) else 57
                val name = line.substringAfter(' ', "packages").substringBefore(' ')
                emit(pct, if (total > 0) "Downloading packages · ${downloaded.coerceAtMost(total)}/$total · $name" else "Downloading packages · $name")
                return
            }

            when {
                line.startsWith("Fetched ") -> emit(62, "Package download complete")
                line.startsWith("Unpacking ") -> {
                    unpacked++
                    val pct = if (total > 0) 63 + (unpacked.coerceAtMost(total) * 4 / total) else 64
                    val name = line.removePrefix("Unpacking ").substringBefore(' ')
                    emit(pct, if (total > 0) "Unpacking Plasma · ${unpacked.coerceAtMost(total)}/$total · $name" else "Unpacking Plasma · $name")
                }
                line.startsWith("Setting up ") -> {
                    configured++
                    val pct = if (total > 0) 68 + (configured.coerceAtMost(total) * 3 / total) else 69
                    val name = line.removePrefix("Setting up ").substringBefore(' ')
                    emit(pct, if (total > 0) "Configuring Plasma · ${configured.coerceAtMost(total)}/$total · $name" else "Configuring Plasma · $name")
                }
                line.startsWith("Processing triggers") -> emit(71, "Finishing Plasma package triggers")
            }
        }
    }

    private fun recoverPackageState() {
        progress("plasma_recovery", 53, "Checking interrupted Debian package state")
        val reporter = PackageProgressReporter("plasma_recovery", 53)
        val cmd = packagePolicyCommand() + "\n" + """
            export DEBIAN_FRONTEND=noninteractive SYSTEMD_OFFLINE=1
            pending=${'$'}(dpkg-query -W -f='${'$'}{db:Status-Abbrev} ${'$'}{binary:Package}\n' 2>/dev/null | awk '${'$'}1 !~ /^ii/ {c++} END {print c+0}')
            echo VESSEL_PENDING_PACKAGES=${'$'}pending
            if [ "${'$'}pending" -gt 0 ]; then
              dpkg --configure -a || {
                apt-get -o Dpkg::Use-Pty=0 -o APT::Color=0 -f install -y
                dpkg --configure -a
              }
            fi
        """.trimIndent()
        val (rc, out) = guestBlocking(cmd, 1800, reporter::onLine)
        if (rc != 0) {
            append("[plasma] interrupted package recovery failed rc=$rc ${out.takeLast(6000)}\n")
            error("Debian package recovery failed (dpkg rc=$rc). See Runtime log for details")
        }
    }

    private fun ensurePlasma() {
        val readyMarker = "/var/cache/vessel/plasma-ready-v58"
        progress("plasma", 53, "Checking persistent Plasma workstation")
        val fastReady = guestBlocking(
            "test -f $readyMarker && command -v kwin_wayland >/dev/null 2>&1 && command -v startplasma-wayland >/dev/null 2>&1 && test -c /dev/dri/card0",
            5,
        )
        if (fastReady.first == 0) {
            append("[plasma] fast-path marker valid; skipped dpkg/APT validation\n")
            return
        }
        if (guestBlocking(plasmaReadyCommand(), 15).first == 0) {
            guestBlocking("install -d -m 755 /var/cache/vessel; touch $readyMarker", 5)
            append("[plasma] existing workstation validated; wrote fast-path marker\n")
            return
        }
        // Only touch dpkg recovery when validation actually failed. Running
        // dpkg --configure -a on every healthy boot made a persistent PC feel
        // like an installer.
        recoverPackageState()
        if (guestBlocking(plasmaReadyCommand(), 20).first == 0) {
            guestBlocking("install -d -m 755 /var/cache/vessel; touch $readyMarker", 5)
            append("[plasma] package recovery restored workstation without reinstall\n")
            return
        }
        progress("plasma_install", 56, "Installing missing Plasma components")
        val reporter = PackageProgressReporter("plasma_install", 56)
        val cmd = packagePolicyCommand() + "\n" +
            "export DEBIAN_FRONTEND=noninteractive SYSTEMD_OFFLINE=1; " +
            "apt-get -o Dpkg::Use-Pty=0 -o APT::Color=0 update && " +
            "apt-get -o Dpkg::Use-Pty=0 -o APT::Color=0 install -y " +
            "kde-plasma-desktop plasma-workspace plasma-desktop kwin-x11 kwin-wayland plasma-workspace-wayland xwayland qtwayland5 wayland-utils systemsettings python3-dbus python3-gi " +
            "xserver-xorg-core xserver-xorg-input-libinput dbus dbus-x11 udev libinput-tools mesa-utils x11-xserver-utils xinput xcvt " +
            "breeze breeze-icon-theme hicolor-icon-theme desktop-file-utils xdg-user-dirs shared-mime-info menu appstream apt-config-icons apt-config-icons-large apt-config-icons-hidpi packagekit packagekit-tools policykit-1 plasma-discover librsvg2-bin python3-yaml " +
            "qml-module-org-kde-qqc2desktopstyle qml-module-org-kde-kirigami2 qml-module-org-kde-kitemmodels qml-module-org-kde-kquickcontrolsaddons " +
            "qml-module-qtquick-controls qml-module-qtquick-controls2 qml-module-qtquick-layouts qml-module-qtquick-window2 qml-module-qtquick2 qml-module-qtquick-templates2 qml-module-qtgraphicaleffects qml-module-qt-labs-platform plasma-integration plasma-pa pulseaudio pulseaudio-utils alsa-utils kactivitymanagerd libkf5service-data " +
            "fonts-noto-core fonts-noto-color-emoji fonts-dejavu-core fonts-liberation firefox-esr konsole dolphin ark kcalc okular gwenview kate && dpkg --configure -a && apt-get clean"
        val (rc, out) = guestBlocking(cmd, 2400, reporter::onLine)
        if (rc != 0) { append("[plasma] apt failed rc=$rc ${out.takeLast(6000)}\n"); error("Plasma Wayland package installation failed (apt rc=$rc)") }
        val metadataRefresh = guestBlocking(
            "appstreamcli refresh-cache --force >/tmp/vessel-appstream-refresh.log 2>&1 || true",
            120,
        )
        if (metadataRefresh.first != 0) append("[apps] metadata/icon refresh rc=${metadataRefresh.first}: ${metadataRefresh.second.takeLast(2000)}\n")
        val verify = guestBlocking(plasmaReadyCommand(), 30)
        if (verify.first != 0) { append("[plasma] validation failed ${verify.second.takeLast(6000)}\n"); error("Plasma Wayland runtime validation failed") }
        guestBlocking("install -d -m 755 /var/cache/vessel; touch $readyMarker", 5)
        progress("plasma_ready", 72, "KDE Plasma Wayland workstation ready")
    }


    private fun guestServicesCommand(): String {
        val audioPort = VesselAudioBridge.port()
        check(audioPort > 0) { "Android audio bridge did not start" }
        val audioHelper = context.assets.open("vessel/guest_audio_pipe.py").use { it.readBytes() }
        val audioHelperB64 = Base64.getEncoder().encodeToString(audioHelper)

        val controlPort = VesselGuestAgent.port()
        check(controlPort > 0) { "Android guest-control server did not start" }
        val controlHelper = context.assets.open("vessel/guest_control_agent.py").use { it.readBytes() }
        val controlHelperB64 = Base64.getEncoder().encodeToString(controlHelper)
        val token = VesselGuestAgent.token()

        // One proven boot-tty transaction installs both service bridges. It
        // starts no long-lived process, so it cannot hold the completion marker.
        val command = """
            set -e
            install -d -m 755 /usr/local/lib/vessel
            printf '%s' '$audioHelperB64' | base64 -d >/usr/local/lib/vessel/audio_pipe.py
            chmod 0755 /usr/local/lib/vessel/audio_pipe.py
            cat >/etc/asound.conf <<'VESSEL_ASOUND'
            pcm.vessel_raw {
                type file
                slave.pcm "null"
                file "|/usr/bin/python3 /usr/local/lib/vessel/audio_pipe.py $audioPort 48000 2 16 S16_LE"
                format "raw"
            }
            pcm.vessel {
                type plug
                slave {
                    pcm "vessel_raw"
                    format S16_LE
                    rate 48000
                    channels 2
                }
            }
            pcm.!default {
                type plug
                slave.pcm "vessel"
            }
            ctl.!default {
                type hw
                card 0
            }
            VESSEL_ASOUND
            install -d -m 700 -o vessel -g vessel /home/vessel/.config/pulse /home/vessel/.config/autostart
            cat >/home/vessel/.config/pulse/default.pa <<'VESSEL_PULSE'
            .include /etc/pulse/default.pa
            load-module module-alsa-sink device=vessel sink_name=vessel sink_properties=device.description=Vessel_Android_Audio
            set-default-sink vessel
            VESSEL_PULSE
            cat >/home/vessel/.config/autostart/vessel-audio.desktop <<'VESSEL_AUDIO_DESKTOP'
            [Desktop Entry]
            Type=Application
            Name=Vessel Android Audio
            Exec=/bin/sh -lc 'pulseaudio --start --exit-idle-time=-1'
            OnlyShowIn=KDE;
            X-KDE-autostart-after=panel
            VESSEL_AUDIO_DESKTOP
            chown -R vessel:vessel /home/vessel/.config/pulse /home/vessel/.config/autostart
            echo VESSEL_AUDIO_READY

            printf '%s' '$controlHelperB64' | base64 -d >/usr/local/lib/vessel/control_agent.py
            chmod 0755 /usr/local/lib/vessel/control_agent.py
            install -d -m 755 /run/vessel
            cat >/run/vessel/control-agent.env <<'VESSEL_CONTROL_ENV'
            VESSEL_CONTROL_HOST=10.0.2.2
            VESSEL_CONTROL_PORT=$controlPort
            VESSEL_CONTROL_TOKEN='$token'
            VESSEL_CONTROL_ENV
            chmod 0600 /run/vessel/control-agent.env
            rm -f /run/vessel-control-agent.pid
            command -v setsid >/dev/null 2>&1 || echo VESSEL_CONTROL_WARNING=setsid-missing
            echo VESSEL_CONTROL_AGENT_PREPARED
            echo VESSEL_BOOT_SERVICES_READY
        """.trimIndent()
        return command
    }

    // X11 is an experimental fallback. It does not use the strict Wayland
    // one-final-RPC path, so retain a blocking service setup helper for it.
    private fun setupGuestServicesBlocking() {
        val audioPort = VesselAudioBridge.port()
        val controlPort = VesselGuestAgent.port()
        val result = guestBlocking(guestServicesCommand(), 45)
        check(result.first == 0 && result.second.contains("VESSEL_BOOT_SERVICES_READY")) {
            "Could not configure guest services: ${result.second.takeLast(7000)}"
        }
        append("[audio] guest PulseAudio/ALSA -> Android AudioTrack bridge configured port=$audioPort\n")
        append("[control] helper/config prepared port=$controlPort\n")
    }

    private fun displayModeCommand(): String {
        val w = displayWidth
        val h = displayHeight
        val dpi = displayDpi
        val rate = displayRefresh.roundToInt().coerceIn(30, 240)
        return """
            export DISPLAY=:0
            out=${'$'}(xrandr --query | awk '/ connected/{print ${'$'}1; exit}')
            test -n "${'$'}out" || exit 2
            cvtbin=${'$'}(command -v cvt || command -v xcvt)
            line=${'$'}(${'$'}cvtbin $w $h $rate 2>/dev/null | sed -n 's/^Modeline //p' | head -1)
            if [ -n "${'$'}line" ]; then
              name=${'$'}(printf '%s\n' "${'$'}line" | sed -n 's/^"\([^"]*\)".*/\1/p')
              eval "xrandr --newmode ${'$'}line" 2>/dev/null || true
              xrandr --addmode "${'$'}out" "${'$'}name" 2>/dev/null || true
              xrandr --output "${'$'}out" --mode "${'$'}name"
            fi
            xrandr --dpi $dpi
        """.trimIndent()
    }

    private fun applyDisplayModeBlocking(): Boolean {
        if (VesselExperimentConfig.desktopBackend(context) == "wayland") return true
        val (rc, out) = guestBlocking(displayModeCommand(), 20)
        if (rc != 0) append("[display] xrandr rc=$rc ${out.takeLast(2000)}\n")
        return rc == 0
    }

    private fun launchDesktop() {
        val backend = VesselExperimentConfig.desktopBackend(context)
        val dmabuf = if (VesselExperimentConfig.firefoxDmabuf(context)) "true" else "false"
        progress("desktop", 72, "Starting Plasma ${if (backend == "wayland") "Wayland" else "X11 fallback"}")
        val prep = """
            set -e
            mkdir -p /run/dbus /run/user /usr/local/bin /home/vessel/.config /home/vessel/.mozilla/firefox/vessel.default
            mountpoint -q /tmp || mount -t tmpfs -o mode=1777,size=256m tmpfs /tmp
            # tmpfs replaced the old /tmp tree, so recreate the Xwayland socket directory.
            mkdir -p /tmp/.X11-unix
            chmod 1777 /tmp/.X11-unix
            mkdir -p /run/user
            mountpoint -q /run/user || mount -t tmpfs -o mode=0755,size=64m tmpfs /run/user
            dbus-uuidgen --ensure=/etc/machine-id
            if ! pgrep -x systemd-udevd >/dev/null 2>&1; then
              timeout 6s /lib/systemd/systemd-udevd --daemon 2>/tmp/vessel-udev.log || timeout 6s /usr/lib/systemd/systemd-udevd --daemon 2>/tmp/vessel-udev.log || true
            fi
            echo VESSEL_PREP_STAGE=udevd-ready
            echo VESSEL_PREP_STAGE=udev
            timeout 8s udevadm trigger --action=add || true
            timeout 12s udevadm settle --timeout=10 || true
            echo VESSEL_PREP_STAGE=udev-ready
            # /run lives on the persistent rootfs, so a dead system bus can leave a
            # stale socket behind across UML boots. Recreate the bus instead of trusting
            # the socket inode, and load the ConsoleKit policy before startup.
            install -d -m 755 /run/dbus /etc/dbus-1/system.d
            cat >/etc/dbus-1/system.d/vessel-consolekit.conf <<'VDBUS'
            <!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-BUS Bus Configuration 1.0//EN"
             "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
            <busconfig>
              <policy user="root">
                <allow own="org.freedesktop.ConsoleKit"/>
                <allow send_destination="org.freedesktop.ConsoleKit"/>
                <allow receive_sender="org.freedesktop.ConsoleKit"/>
              </policy>
              <policy context="default">
                <allow send_destination="org.freedesktop.ConsoleKit"/>
                <allow receive_sender="org.freedesktop.ConsoleKit"/>
              </policy>
            </busconfig>
            VDBUS
            # No user session bus exists at this stage, so terminate any stale/system
            # dbus-daemon left by an earlier prep attempt and create one known-good bus.
            pkill -x dbus-daemon 2>/dev/null || true
            for i in ${'$'}(seq 1 40); do pgrep -x dbus-daemon >/dev/null || break; sleep .05; done
            pgrep -x dbus-daemon >/dev/null && pkill -KILL -x dbus-daemon 2>/dev/null || true
            rm -f /run/dbus/system_bus_socket /run/dbus/pid
            : >/tmp/vessel-dbus.log
            timeout 8s dbus-daemon --system --fork 2>/tmp/vessel-dbus.log || { echo VESSEL_DBUS_START_FAILED; cat /tmp/vessel-dbus.log; exit 48; }
            for i in ${'$'}(seq 1 80); do
              dbus-send --system --print-reply --dest=org.freedesktop.DBus / org.freedesktop.DBus.ListNames >/dev/null 2>&1 && break
              sleep .1
            done
            dbus-send --system --print-reply --dest=org.freedesktop.DBus / org.freedesktop.DBus.ListNames >/dev/null 2>&1 || { echo VESSEL_DBUS_HEALTHCHECK_FAILED; cat /tmp/vessel-dbus.log 2>/dev/null || true; exit 48; }
            echo VESSEL_PREP_STAGE=dbus-ready
            id -u vessel >/dev/null 2>&1 || useradd -m -s /bin/bash vessel
            for g in video render input; do getent group "${'$'}g" >/dev/null || groupadd "${'$'}g"; done
            usermod -a -G video,render,input vessel
            install -d -m 755 /etc/polkit-1/rules.d
            cat >/etc/polkit-1/rules.d/49-vessel-packagekit.rules <<'VESSEL_POLKIT'
            polkit.addRule(function(action, subject) {
                if (subject.user == "vessel" && action.id.indexOf("org.freedesktop.packagekit.") == 0) {
                    return polkit.Result.YES;
                }
            });
            VESSEL_POLKIT
            chmod 0644 /etc/polkit-1/rules.d/49-vessel-packagekit.rules
            if [ -x /usr/lib/polkit-1/polkitd ] && ! pgrep -x polkitd >/dev/null 2>&1; then
              /usr/lib/polkit-1/polkitd --no-debug >/tmp/vessel-polkit.log 2>&1 &
            fi
            appstreamcli refresh-cache --force >/tmp/vessel-appstream-refresh.log 2>&1 || true
            pkcon get-roles >/tmp/vessel-packagekit.log 2>&1 || true
            uid=${'$'}(id -u vessel); gid=${'$'}(id -g vessel)
            mkdir -p /run/user/${'$'}uid; chown ${'$'}uid:${'$'}gid /run/user/${'$'}uid; chmod 700 /run/user/${'$'}uid
            test -c /dev/tty1 || mknod -m 620 /dev/tty1 c 4 1
            # KWin 5.27 requires a real session object for DRM/input fd acquisition.
            # Vessel has no logind PID1, so expose a minimal ConsoleKit-compatible
            # session broker that opens devices as root and passes the fds via D-Bus.
            install -d -m 755 /usr/local/lib/vessel
            cat >/usr/local/lib/vessel/consolekit_shim.py <<'VCK'
            #!/usr/bin/python3
            import os
            import stat
            import dbus
            import dbus.service
            from dbus.mainloop.glib import DBusGMainLoop
            from gi.repository import GLib

            SERVICE = 'org.freedesktop.ConsoleKit'
            MANAGER = '/org/freedesktop/ConsoleKit/Manager'
            SESSION = '/org/freedesktop/ConsoleKit/Session1'
            SEAT = '/org/freedesktop/ConsoleKit/Seat1'
            MANAGER_IF = 'org.freedesktop.ConsoleKit.Manager'
            SESSION_IF = 'org.freedesktop.ConsoleKit.Session'
            SEAT_IF = 'org.freedesktop.ConsoleKit.Seat'
            PROPS_IF = 'org.freedesktop.DBus.Properties'

            def device_path(major_num, minor_num):
                preferred = ['/dev/dri/card0', '/dev/dri/renderD128']
                for base in ('/dev/input', '/dev/dri'):
                    try:
                        preferred.extend(os.path.join(base, x) for x in os.listdir(base))
                    except OSError:
                        pass
                for path in preferred:
                    try:
                        st = os.stat(path)
                    except OSError:
                        continue
                    if stat.S_ISCHR(st.st_mode) and os.major(st.st_rdev) == major_num and os.minor(st.st_rdev) == minor_num:
                        return path
                raise dbus.exceptions.DBusException('org.freedesktop.ConsoleKit.Error.Failed', f'device {major_num}:{minor_num} not found')

            class Manager(dbus.service.Object):
                @dbus.service.method(MANAGER_IF, in_signature='u', out_signature='o')
                def GetSessionByPID(self, pid):
                    return dbus.ObjectPath(SESSION)

            class Session(dbus.service.Object):
                @dbus.service.method(SESSION_IF, in_signature='b', out_signature='')
                def TakeControl(self, force):
                    return

                @dbus.service.method(SESSION_IF, in_signature='', out_signature='')
                def ReleaseControl(self):
                    return

                @dbus.service.method(SESSION_IF, in_signature='', out_signature='')
                def Activate(self):
                    return

                @dbus.service.method(SESSION_IF, in_signature='uu', out_signature='h')
                def TakeDevice(self, major_num, minor_num):
                    path = device_path(int(major_num), int(minor_num))
                    fd = os.open(path, os.O_RDWR | os.O_CLOEXEC | os.O_NONBLOCK)
                    try:
                        return dbus.types.UnixFd(fd)
                    finally:
                        os.close(fd)

                @dbus.service.method(SESSION_IF, in_signature='uu', out_signature='')
                def ReleaseDevice(self, major_num, minor_num):
                    return

                @dbus.service.method(PROPS_IF, in_signature='ss', out_signature='v')
                def Get(self, interface, prop):
                    if interface != SESSION_IF:
                        raise dbus.exceptions.DBusException('org.freedesktop.DBus.Error.InvalidArgs', 'unknown interface')
                    if prop == 'active':
                        return dbus.Boolean(True, variant_level=1)
                    if prop == 'VTNr':
                        return dbus.UInt32(1, variant_level=1)
                    if prop == 'Seat':
                        return dbus.Struct((dbus.String('seat0'), dbus.ObjectPath(SEAT)), signature='so', variant_level=1)
                    raise dbus.exceptions.DBusException('org.freedesktop.DBus.Error.InvalidArgs', 'unknown property')

            class Seat(dbus.service.Object):
                @dbus.service.method(SEAT_IF, in_signature='u', out_signature='')
                def SwitchTo(self, terminal):
                    return

            DBusGMainLoop(set_as_default=True)
            bus = dbus.SystemBus()
            name = dbus.service.BusName(SERVICE, bus=bus, do_not_queue=True)
            Manager(bus, MANAGER)
            Session(bus, SESSION)
            Seat(bus, SEAT)
            print('VESSEL_CONSOLEKIT_READY', flush=True)
            GLib.MainLoop().run()
            VCK
            chmod 0755 /usr/local/lib/vessel/consolekit_shim.py
            pkill -f '/usr/local/lib/vessel/consolekit_shim.py' 2>/dev/null || true
            setsid -f /usr/bin/python3 /usr/local/lib/vessel/consolekit_shim.py </dev/null >/tmp/vessel-consolekit.log 2>&1
            for i in ${'$'}(seq 1 80); do
              dbus-send --system --print-reply --dest=org.freedesktop.DBus / org.freedesktop.DBus.NameHasOwner string:org.freedesktop.ConsoleKit 2>/dev/null | grep -q 'boolean true' && break
              sleep .1
            done
            dbus-send --system --print-reply --dest=org.freedesktop.DBus / org.freedesktop.DBus.NameHasOwner string:org.freedesktop.ConsoleKit 2>/dev/null | grep -q 'boolean true' || { cat /tmp/vessel-consolekit.log; exit 47; }
            echo VESSEL_PREP_STAGE=consolekit-ready
            # Keep ordinary unix permissions sane too; the broker still owns the fd handoff.
            test ! -c /dev/dri/card0 || { chgrp video /dev/dri/card0 || true; chmod 0660 /dev/dri/card0 || true; }
            test ! -c /dev/dri/renderD128 || { chgrp render /dev/dri/renderD128 || true; chmod 0660 /dev/dri/renderD128 || true; }
            rm -f /etc/X11/xorg.conf.d/99-vessel.conf
            cat >/etc/profile.d/vessel-gpu.sh <<'VENV'
            export LIBGL_ALWAYS_SOFTWARE=0
            export GALLIUM_DRIVER=virgl
            export GDK_BACKEND=wayland
            export QT_QPA_PLATFORM=wayland
            export CLUTTER_BACKEND=wayland
            export SDL_VIDEODRIVER=wayland
            export MOZ_ENABLE_WAYLAND=1
            export MOZ_WEBRENDER=1
            export MOZ_ACCELERATED=1
            export MOZ_DISABLE_CONTENT_SANDBOX=1
            export XCURSOR_THEME=Breeze
            export XCURSOR_SIZE=24
            unset MOZ_X11_EGL
            VENV
            chmod 0644 /etc/profile.d/vessel-gpu.sh
            cat >/home/vessel/.mozilla/firefox/profiles.ini <<'FPROFILES'
            [Profile0]
            Name=Vessel
            IsRelative=1
            Path=vessel.default
            Default=1
            [General]
            StartWithLastProfile=1
            Version=2
            FPROFILES
            cat >/home/vessel/.mozilla/firefox/vessel.default/user.js <<FUSER
            user_pref("gfx.webrender.all", true);
            user_pref("gfx.webrender.compositor", false);
            user_pref("widget.dmabuf-textures.enabled", $dmabuf);
            user_pref("widget.dmabuf-webgl.enabled", $dmabuf);
            user_pref("gfx.x11-egl.force-disabled", true);
            user_pref("gl.require-hardware", true);
            user_pref("security.sandbox.content.level", 0);
            FUSER
            chown vessel:vessel /home/vessel/.mozilla /home/vessel/.mozilla/firefox /home/vessel/.mozilla/firefox/vessel.default /home/vessel/.config
            chown vessel:vessel /home/vessel/.mozilla/firefox/profiles.ini /home/vessel/.mozilla/firefox/vessel.default/user.js
            echo VESSEL_PREP_STAGE=profile-ready
            cat >/usr/local/bin/vessel-plasma-session <<'VSESSION'
            #!/bin/bash
            set -e
            export XDG_RUNTIME_DIR=/run/user/${'$'}(id -u)
            export XDG_SESSION_TYPE=wayland XDG_SESSION_DESKTOP=KDE XDG_CURRENT_DESKTOP=KDE DESKTOP_SESSION=plasmawayland
            export XDG_SESSION_CLASS=user XDG_SEAT=seat0 XDG_VTNR=1 KDE_FULL_SESSION=true KDE_SESSION_VERSION=5
            export LIBGL_ALWAYS_SOFTWARE=0 GALLIUM_DRIVER=virgl
            export GDK_BACKEND=wayland QT_QPA_PLATFORM=wayland CLUTTER_BACKEND=wayland SDL_VIDEODRIVER=wayland
            export MOZ_ENABLE_WAYLAND=1 MOZ_WEBRENDER=1 MOZ_ACCELERATED=1 MOZ_DISABLE_CONTENT_SANDBOX=1
            export XCURSOR_THEME=Breeze XCURSOR_SIZE=24
            unset DISPLAY MOZ_X11_EGL
            exec startplasma-wayland
            VSESSION
            chmod 0755 /usr/local/bin/vessel-plasma-session
            cat >/usr/local/lib/vessel/launch_wayland.py <<'VLAUNCH'
            #!/usr/bin/python3
            import os
            import subprocess
            import sys

            uid = subprocess.check_output(['/usr/bin/id', '-u', 'vessel'], text=True).strip()
            env_command = (
                f'XDG_RUNTIME_DIR=/run/user/{uid} XDG_SEAT=seat0 XDG_VTNR=1 '
                'exec dbus-run-session -- /usr/local/bin/vessel-plasma-session'
            )
            log = open('/tmp/vessel-plasma.log', 'ab', buffering=0)
            try:
                proc = subprocess.Popen(
                    ['/usr/bin/su', '-l', 'vessel', '-c', env_command],
                    stdin=subprocess.DEVNULL,
                    stdout=log,
                    stderr=subprocess.STDOUT,
                    cwd='/home/vessel',
                    close_fds=True,
                    start_new_session=True,
                )
            except Exception:
                log.close()
                raise
            print(f'VESSEL_WAYLAND_PID={proc.pid}', flush=True)
            VLAUNCH
            chmod 0755 /usr/local/lib/vessel/launch_wayland.py
        """.trimIndent()
        var preparedDesktop = prep
        if (backend == "wayland") {
            preparedDesktop += "\n" + guestServicesCommand()
            append("[desktop] guest services folded into final authoritative tty RPC\n")
        }
        var waylandReadyInPrep = false
        if (backend == "wayland") {
            // Take one atomic snapshot of the hot runtime. If an update races
            // this boot, use the APK's built-in bootstrap rather than mixing
            // files from two revisions.
            val hotRevisionBefore = VesselUpdateManager.currentRuntimeRevision(context)
            val stagedOverrides = listOf(
                "wayland-session.sh" to "/usr/local/bin/vessel-plasma-session",
                "launch-wayland.py" to "/usr/local/lib/vessel/launch_wayland.py",
            ).mapNotNull { (liveName, guestPath) ->
                VesselUpdateManager.runtimeScriptOrNull(context, liveName)?.let { Triple(liveName, guestPath, it) }
            }
            val stagedPostPrep = VesselUpdateManager.runtimeScriptOrNull(context, "wayland-postprep.sh")
            val hotRevisionAfter = VesselUpdateManager.currentRuntimeRevision(context)
            var effectivePostPrep: String? = null

            if (hotRevisionBefore == hotRevisionAfter) {
                for ((liveName, guestPath, liveText) in stagedOverrides) {
                    val liveB64 = Base64.getEncoder().encodeToString(liveText.toByteArray())
                    preparedDesktop += "\nprintf '%s' '$liveB64' | base64 -d >'$guestPath'; chmod 0755 '$guestPath'"
                    append("[update] staged $liveName from hot runtime $hotRevisionAfter into desktop prep\\n")
                }
                effectivePostPrep = stagedPostPrep
                if (effectivePostPrep != null) {
                    append("[update] staged authoritative Wayland bootstrap from hot runtime $hotRevisionAfter\\n")
                }
            } else {
                append("[update] hot runtime changed during boot snapshot ($hotRevisionBefore -> $hotRevisionAfter); using built-in Wayland bootstrap\\n")
            }

            if (effectivePostPrep == null) {
                effectivePostPrep = String(Base64.getDecoder().decode("IyEvYmluL2Jhc2gKc2V0IC1ldQoKZWNobyBWRVNTRUxfV0FZTEFORF9CT09UU1RSQVBfQkVHSU4KaWYgISBwZ3JlcCAtdSB2ZXNzZWwgLXgga3dpbl93YXlsYW5kID4vZGV2L251bGwgMj4mMTsgdGhlbgogIHBraWxsIC11IHZlc3NlbCAteCBrd2luX3gxMSAyPi9kZXYvbnVsbCB8fCB0cnVlCiAgcGtpbGwgLXUgdmVzc2VsIC14IGt3aW5fd2F5bGFuZCAyPi9kZXYvbnVsbCB8fCB0cnVlCiAgcGtpbGwgLXUgdmVzc2VsIC14IHBsYXNtYXNoZWxsIDI+L2Rldi9udWxsIHx8IHRydWUKICBwa2lsbCAteCBYb3JnIDI+L2Rldi9udWxsIHx8IHRydWUKICBybSAtZiAvdG1wLy5YMC1sb2NrIC90bXAvLlgxMS11bml4L1gwCiAgZmluZCAvcnVuL3VzZXIgLW1heGRlcHRoIDIgLXR5cGUgcyAtbmFtZSAnd2F5bGFuZC0qJyAtZGVsZXRlIDI+L2Rldi9udWxsIHx8IHRydWUKICA6ID4vdG1wL3Zlc3NlbC1wbGFzbWEubG9nCiAgL3Vzci9iaW4vcHl0aG9uMyAvdXNyL2xvY2FsL2xpYi92ZXNzZWwvbGF1bmNoX3dheWxhbmQucHkKZmkKCmZvciBpIGluICQoc2VxIDEgNjAwKTsgZG8KICBpZiBwZ3JlcCAtdSB2ZXNzZWwgLXgga3dpbl93YXlsYW5kID4vZGV2L251bGwgMj4mMSAmJiBcCiAgICAgcGdyZXAgLXUgdmVzc2VsIC14IHBsYXNtYXNoZWxsID4vZGV2L251bGwgMj4mMSAmJiBcCiAgICAgZmluZCAvcnVuL3VzZXIgLW1heGRlcHRoIDIgLXR5cGUgcyAtbmFtZSAnd2F5bGFuZC0qJyAtcHJpbnQgLXF1aXQgMj4vZGV2L251bGwgfCBncmVwIC1xIC47IHRoZW4KICAgIGVjaG8gVkVTU0VMX1dBWUxBTkRfUkVBRFkKICAgIGV4aXQgMAogIGZpCiAgc2xlZXAgLjEKZG9uZQoKZWNobyBWRVNTRUxfV0FZTEFORF9ESUFHCmlkIHZlc3NlbCB8fCB0cnVlCmRwa2ctcXVlcnkgLVcga3dpbi13YXlsYW5kIGt3aW4tY29tbW9uIHBsYXNtYS13b3Jrc3BhY2Utd2F5bGFuZCAyPi9kZXYvbnVsbCB8fCB0cnVlCmxzIC1sIC9kZXYvZHJpIDI+L2Rldi9udWxsIHx8IHRydWUKbHMgLWxhIC9ydW4vdXNlci8qIDI+L2Rldi9udWxsIHx8IHRydWUKbHMgLWxkIC90bXAvLlgxMS11bml4IDI+L2Rldi9udWxsIHx8IHRydWUKZGJ1cy1zZW5kIC0tc3lzdGVtIC0tcHJpbnQtcmVwbHkgLS1kZXN0PW9yZy5mcmVlZGVza3RvcC5EQnVzIC8gb3JnLmZyZWVkZXNrdG9wLkRCdXMuTmFtZUhhc093bmVyIHN0cmluZzpvcmcuZnJlZWRlc2t0b3AuQ29uc29sZUtpdCAyPi9kZXYvbnVsbCB8fCB0cnVlCmNhdCAvdG1wL3Zlc3NlbC1jb25zb2xla2l0LmxvZyAyPi9kZXYvbnVsbCB8fCB0cnVlCnRhaWwgLTQwMCAvdG1wL3Zlc3NlbC1wbGFzbWEubG9nIDI+L2Rldi9udWxsIHx8IHRydWUKZXhpdCA0NAo="), Charsets.UTF_8)
                append("[update] using built-in authoritative Wayland bootstrap\\n")
            }

            val postB64 = Base64.getEncoder().encodeToString(effectivePostPrep.toByteArray())
            preparedDesktop += "\nprintf '%s' '$postB64' | base64 -d | /bin/bash"
            preparedDesktop += "\nprintf '%s' 'IyEvYmluL2Jhc2gKc2V0ICtlCmNmZz0vcnVuL3Zlc3NlbC9jb250cm9sLWFnZW50LmVudgpwaWRmaWxlPS9ydW4vdmVzc2VsLWNvbnRyb2wtYWdlbnQucGlkCmFnZW50PS91c3IvbG9jYWwvbGliL3Zlc3NlbC9jb250cm9sX2FnZW50LnB5CmxvZz0vdG1wL3Zlc3NlbC1jb250cm9sLWFnZW50LmxvZwoKaWYgWyAhIC1yICIkY2ZnIiBdIHx8IFsgISAteCAiJGFnZW50IiBdOyB0aGVuCiAgZWNobyBWRVNTRUxfQ09OVFJPTF9BR0VOVF9TS0lQUEVEPW5vdC1wcmVwYXJlZAogIGV4aXQgMApmaQppZiAhIGNvbW1hbmQgLXYgc2V0c2lkID4vZGV2L251bGwgMj4mMTsgdGhlbgogIGVjaG8gVkVTU0VMX0NPTlRST0xfQUdFTlRfU0tJUFBFRD1zZXRzaWQtbWlzc2luZwogIGV4aXQgMApmaQoKLiAiJGNmZyIKaWYgWyAteiAiJHtWRVNTRUxfQ09OVFJPTF9QT1JUOi19IiBdIHx8IFsgLXogIiR7VkVTU0VMX0NPTlRST0xfVE9LRU46LX0iIF07IHRoZW4KICBlY2hvIFZFU1NFTF9DT05UUk9MX0FHRU5UX1NLSVBQRUQ9YmFkLWNvbmZpZwogIGV4aXQgMApmaQoKb2xkX3BpZD0kKGNhdCAiJHBpZGZpbGUiIDI+L2Rldi9udWxsIHx8IHRydWUpCmlmIFsgLW4gIiRvbGRfcGlkIiBdICYmIFsgLXIgIi9wcm9jLyRvbGRfcGlkL2NtZGxpbmUiIF07IHRoZW4KICBpZiB0ciAnXDAwMCcgJyAnIDwiL3Byb2MvJG9sZF9waWQvY21kbGluZSIgMj4vZGV2L251bGwgfCBncmVwIC1GcSAiJGFnZW50IjsgdGhlbgogICAga2lsbCAiJG9sZF9waWQiIDI+L2Rldi9udWxsIHx8IHRydWUKICAgIGZvciBfIGluICQoc2VxIDEgMjApOyBkbwogICAgICBraWxsIC0wICIkb2xkX3BpZCIgMj4vZGV2L251bGwgfHwgYnJlYWsKICAgICAgc2xlZXAgLjA1CiAgICBkb25lCiAgICBraWxsIC1LSUxMICIkb2xkX3BpZCIgMj4vZGV2L251bGwgfHwgdHJ1ZQogIGZpCmZpCnJtIC1mICIkcGlkZmlsZSIKOiA+IiRsb2ciCgojIC1mIGFsd2F5cyBmb3Jrcy4gV2UgaW50ZW50aW9uYWxseSBkbyBOT1QgcGFzcyAtdywgc28gc2V0c2lkIGl0c2VsZiByZXR1cm5zCiMgaW1tZWRpYXRlbHkgd2hpbGUgdGhlIHJvb3QgY29udHJvbCBhZ2VudCBsaXZlcyBpbiBhIHNlcGFyYXRlIHNlc3Npb24uCnNldHNpZCAtZiAvdXNyL2Jpbi9weXRob24zICIkYWdlbnQiIFwKICAiJHtWRVNTRUxfQ09OVFJPTF9IT1NUOi0xMC4wLjIuMn0iICIkVkVTU0VMX0NPTlRST0xfUE9SVCIgIiRWRVNTRUxfQ09OVFJPTF9UT0tFTiIgXAogIDwvZGV2L251bGwgPj4iJGxvZyIgMj4mMQpzcGF3bl9yYz0kPwppZiBbICIkc3Bhd25fcmMiIC1lcSAwIF07IHRoZW4KICBlY2hvIFZFU1NFTF9DT05UUk9MX0FHRU5UX0RJU1BBVENIRUQKZWxzZQogIGVjaG8gVkVTU0VMX0NPTlRST0xfQUdFTlRfU0tJUFBFRD1zZXRzaWQtcmMtJHNwYXduX3JjCmZpCmV4aXQgMAo=' | base64 -d | /bin/bash"
            waylandReadyInPrep = true
        }
        append("[desktop] authoritative single-RPC prep + Wayland bootstrap\n")
        append("[desktop] v57 authoritative ONE final tty RPC: services + prep + Wayland readiness\n")
        val prepResult = guestBlocking(preparedDesktop, 150) { raw ->
            when {
                raw.contains("VESSEL_AUDIO_READY") ->
                    progress("desktop_services", 73, "Linux audio bridge prepared")
                raw.contains("VESSEL_CONTROL_AGENT_PREPARED") ->
                    progress("desktop_control", 74, "Linux control service prepared")
                raw.contains("VESSEL_PREP_STAGE=profile-ready") ->
                    progress("desktop_profile", 75, "Desktop profile ready")
                raw.contains("VESSEL_PREP_STAGE=udevd-ready") ->
                    progress("desktop_devices", 76, "Desktop device service ready")
                raw.contains("VESSEL_PREP_STAGE=udev-ready") ->
                    progress("desktop_devices", 77, "Desktop devices ready")
                raw.contains("VESSEL_PREP_STAGE=dbus-ready") ->
                    progress("desktop_dbus", 79, "Wayland system bus ready")
                raw.contains("VESSEL_PREP_STAGE=consolekit-ready") ->
                    progress("desktop_session", 81, "DRM session broker ready")
                raw.contains("VESSEL_WAYLAND_BOOTSTRAP_BEGIN") ->
                    progress("desktop_launch", 83, "Launching KWin Wayland")
                raw.contains("VESSEL_CONTROL_AGENT_DISPATCHED") ->
                    progress("desktop_control_live", 87, "Desktop control service starting")
                raw.contains("VESSEL_WAYLAND_READY") ->
                    progress("desktop_ready", 88, "Plasma Wayland ready")
            }
        }
        check(prepResult.first == 0) { "desktop prep failed: ${prepResult.second.takeLast(8000)}" }

        if (backend == "wayland" && waylandReadyInPrep) {
            append("[desktop] authoritative Wayland prep RPC completed; KWin + Plasma + Wayland socket are ready\n")
            return
        }

        if (backend == "wayland") {
            val session = """
                #!/bin/bash
                set -e
                export XDG_RUNTIME_DIR=/run/user/${'$'}(id -u)
                export XDG_SESSION_TYPE=wayland XDG_SESSION_DESKTOP=KDE XDG_CURRENT_DESKTOP=KDE DESKTOP_SESSION=plasmawayland
                export XDG_SEAT=seat0 XDG_VTNR=1 KDE_FULL_SESSION=true KDE_SESSION_VERSION=5
                export LIBGL_ALWAYS_SOFTWARE=0 GALLIUM_DRIVER=virgl
                export GDK_BACKEND=wayland QT_QPA_PLATFORM=wayland CLUTTER_BACKEND=wayland SDL_VIDEODRIVER=wayland
                export MOZ_ENABLE_WAYLAND=1 MOZ_WEBRENDER=1 MOZ_ACCELERATED=1
                unset MOZ_X11_EGL
                exec startplasma-wayland
            """.trimIndent() + "\n"
            val b64 = Base64.getEncoder().encodeToString(session.toByteArray())
            val cleanup = VesselUpdateManager.runtimeScript(context, "wayland-cleanup.sh", """
                #!/bin/bash
                set -eu
                pkill -u vessel -x kwin_x11 2>/dev/null || true
                pkill -u vessel -x kwin_wayland 2>/dev/null || true
                pkill -u vessel -x plasmashell 2>/dev/null || true
                pkill -x Xorg 2>/dev/null || true
                rm -f /tmp/.X0-lock /tmp/.X11-unix/X0
                find /run/user -maxdepth 2 -type s -name 'wayland-*' -delete 2>/dev/null || true
                : >/tmp/vessel-plasma.log
                echo VESSEL_WAYLAND_CLEAN
            """.trimIndent())
            val cleanupResult = guestBlocking(cleanup, 45)
            check(cleanupResult.first == 0 && cleanupResult.second.contains("VESSEL_WAYLAND_CLEAN")) { "Wayland cleanup failed: ${cleanupResult.second.takeLast(8000)}" }
            append("[desktop] Wayland stage 1/3: stale desktop state cleaned\\n")

            val dispatchResult = guestBlocking("/usr/bin/python3 /usr/local/lib/vessel/launch_wayland.py && echo VESSEL_WAYLAND_DISPATCHED", 45)
            check(dispatchResult.first == 0 && dispatchResult.second.contains("VESSEL_WAYLAND_DISPATCHED")) { "Plasma Wayland dispatch failed: ${dispatchResult.second.takeLast(10000)}" }
            append("[desktop] Wayland stage 2/3: fully detached Plasma session dispatched\\n")
            val checkCommand = VesselUpdateManager.runtimeScript(context, "wayland-check.sh", """
                #!/bin/bash
                for i in $(seq 1 600); do
                  if pgrep -u vessel -x kwin_wayland >/dev/null && pgrep -u vessel -x plasmashell >/dev/null && find /run/user -maxdepth 2 -type s -name 'wayland-*' -print -quit 2>/dev/null | grep -q .; then
                    echo VESSEL_WAYLAND_READY
                    exit 0
                  fi
                  sleep .1
                done
                echo VESSEL_WAYLAND_DIAG
                id vessel || true
                dpkg-query -W kwin-wayland kwin-common plasma-workspace-wayland 2>/dev/null || true
                ls -l /dev/dri 2>/dev/null || true
                ls -la /run/user/* 2>/dev/null || true
                ls -ld /tmp/.X11-unix 2>/dev/null || true
                dbus-send --system --print-reply --dest=org.freedesktop.DBus / org.freedesktop.DBus.NameHasOwner string:org.freedesktop.ConsoleKit 2>/dev/null || true
                cat /tmp/vessel-consolekit.log 2>/dev/null || true
                tail -400 /tmp/vessel-plasma.log 2>/dev/null || true
                exit 44
            """.trimIndent())
            val check = guestBlocking(checkCommand, 75)
            check(check.first == 0) { "Plasma Wayland validation failed: ${check.second.takeLast(10000)}" }
            append("[desktop] Wayland stage 3/3: native KWin DRM + Plasma + Xwayland ready\n")
        } else {
            val xprep = "mkdir -p /etc/X11/xorg.conf.d /tmp/.X11-unix; cat >/etc/X11/xorg.conf.d/99-vessel.conf <<'XEOF'\nSection \"Device\"\n Identifier \"Vessel GPU\"\n Driver \"modesetting\"\n Option \"kmsdev\" \"/dev/dri/card0\"\n Option \"AccelMethod\" \"glamor\"\n Option \"SWcursor\" \"true\"\nEndSection\nXEOF\n"
            check(guestBlocking(xprep, 20).first == 0)
            val session = "#!/bin/bash\nexport DISPLAY=:0 XDG_SESSION_TYPE=x11 XDG_SESSION_DESKTOP=KDE XDG_CURRENT_DESKTOP=KDE DESKTOP_SESSION=plasma KDE_FULL_SESSION=true KDE_SESSION_VERSION=5 LIBGL_ALWAYS_SOFTWARE=0 GALLIUM_DRIVER=virgl MOZ_WEBRENDER=1\nexport XDG_RUNTIME_DIR=/run/user/\$(id -u)\nexec startplasma-x11\n"
            val b64 = Base64.getEncoder().encodeToString(session.toByteArray())
            val launch = "printf '%s' '$b64' | base64 -d >/usr/local/bin/vessel-plasma-session; chmod 755 /usr/local/bin/vessel-plasma-session; pkill -u vessel -x kwin_wayland 2>/dev/null || true; pkill -u vessel -x plasmashell 2>/dev/null || true; rm -f /tmp/.X0-lock /tmp/.X11-unix/X0; nohup setsid sh -c 'exec </dev/tty1 >/dev/tty1 2>&1; exec env LIBGL_ALWAYS_SOFTWARE=0 GALLIUM_DRIVER=virgl Xorg :0 -ac -noreset -nolisten tcp -novtswitch -sharevts vt1' >/tmp/vessel-xorg.log 2>&1 & for i in \$(seq 1 160); do test -S /tmp/.X11-unix/X0 && break; sleep .1; done; test -S /tmp/.X11-unix/X0; nohup su -l vessel -c \"DISPLAY=:0 XDG_RUNTIME_DIR=/run/user/\$(id -u vessel) MOZ_WEBRENDER=1 dbus-run-session -- /usr/local/bin/vessel-plasma-session\" >/tmp/vessel-plasma.log 2>&1 </dev/null &"
            val lr = guestBlocking(launch, 50); check(lr.first == 0) { "Plasma X11 fallback launch failed: ${lr.second.takeLast(10000)}" }
            applyDisplayModeBlocking()
            val check = guestBlocking("for i in \$(seq 1 120); do pgrep -u vessel -x plasmashell >/dev/null && pgrep -u vessel -x kwin_x11 >/dev/null && break; sleep .1; done; pgrep -u vessel -x plasmashell >/dev/null && pgrep -u vessel -x kwin_x11 >/dev/null", 30)
            check(check.first == 0) { "Plasma X11 fallback validation failed" }
            append("[desktop] X11 fallback ready\n")
        }
    }

    private fun displayFailureStatus(status: String): Boolean =
        status.contains("missing-") || status.contains("failed") || status.contains("rejected") || status.startsWith("presenter-error")

    suspend fun startDesktop(): JSONObject = withContext(Dispatchers.IO) {
        if (running) return@withContext status()
        stopping = false
        lastError = ""
        desktopReady = false
        try {
            assertAssets()
            useGuestAgent = false
            VesselGuestAgent.resetConnection()
            killStaleNativeRuntimeProcesses("pre-start")
            ensureDisk()
            persistentLog.writeText("Vessel ${REVISION} startup\n")
            append("[host] machine=${machineDir.absolutePath}\n")
            append("[host] presenter=${VesselWaylandPresenter.status()}\n")
            progress("input_backend", 28, "Starting native VirtIO input devices")
            startInputBackends()
            progress("gpu", 31, "Starting native VirtIO GPU")
            startGpu()
            progress("uml", 36, "Booting Debian ARM64 · ${guestMemoryMb} MiB · $selectedVcpus vCPU")
            startUml()
            startedAt = android.os.SystemClock.elapsedRealtime()
            running = true
            progress("guest_boot", 40, "Waiting for Debian userspace")
            awaitGuestShell(240)
            ensureGuestNetworkBlocking()
            ensureGuestFilesystemCapacity()
            val ready = guestBlocking("stty -echo 2>/dev/null || true; test -c /dev/dri/card0 && test -c /dev/dri/renderD128", 30)
            check(ready.first == 0) { "Debian/VirtIO GPU did not become ready: ${ready.second.takeLast(8000)}" }
            guestReady = true
            progress("input", 48, "Verifying native VirtIO evdev/libinput devices")
            awaitVirtioInputDevices()
            ensurePlasma()
            if (VesselExperimentConfig.desktopBackend(context) == "x11") {
                setupGuestServicesBlocking()
            }
            launchDesktop()
            // From this point forward tty0 is never used for app/terminal/stats
            // commands. The agent reconnects independently and cannot fail boot.
            useGuestAgent = true
            if (VesselGuestAgent.waitUntilConnected(8_000)) {
                append("[control] persistent Debian control agent connected; post-boot RPC left tty0 permanently\n")
            } else {
                append("[control] desktop is ready but agent is still reconnecting (${VesselGuestAgent.status()}); boot continues and post-boot calls stay off tty0\n")
            }
            progress("frame", 88, "Waiting for Android native Surface frame")

            var tries = 0
            while (tries++ < 600) {
                if (stopping) return@withContext baseState()
                val ps = VesselWaylandPresenter.status()
                if (presenterVisible(ps)) {
                    desktopReady = true
                    lastError = ""
                    progress("ready", 100, "Plasma visible through Android native Surface")
                    return@withContext baseState().put("presenter", ps)
                }
                if (displayFailureStatus(ps)) {
                    lastError = "Native presenter issue: $ps"
                    append("[display] $lastError; Linux kept running for diagnostics\n")
                    progress("display_issue", 94, "Desktop running · presenter needs attention")
                    return@withContext baseState(false).put("presenter", ps)
                }
                if (tries >= 20 && (ps == "surface-detached" || ps.contains("waiting-for-surface"))) {
                    progress("display_wait", 94, "Desktop running · open Display to attach the Android surface")
                    append("[display] desktop is running; waiting for Android display surface\n")
                    return@withContext baseState().put("presenter", ps)
                }
                Thread.sleep(50)
            }

            val ps = VesselWaylandPresenter.status()
            lastError = "Desktop is running, but no Android native Surface frame has arrived yet; presenter=$ps"
            append("[display] $lastError; Linux kept running for diagnostics\n")
            progress("display_wait", 94, "Desktop running · waiting for first GPU frame")
            baseState(false).put("presenter", ps)
        } catch (t: Throwable) {
            if (stopping) {
                append("[host] startup stopped by user\n")
                return@withContext baseState()
            }
            lastError = t.message ?: t.javaClass.simpleName
            append("[error] $lastError\n")
            stopBlocking()
            throw t
        }
    }

    suspend fun guest(command: String, timeoutSeconds: Int = 45): JSONObject = withContext(Dispatchers.IO) {
        val (rc, out) = guestBlocking(command, timeoutSeconds)
        baseState(rc == 0).put("rc", rc).put("output", out).also {
            if (rc != 0) it.put("error", "guest command failed rc=$rc")
        }
    }

    private fun stopBlocking() {
        stopping = true
        if (useGuestAgent && VesselGuestAgent.isConnected()) {
            runCatching {
                VesselGuestAgent.execute("sync; pkill -u vessel -x plasmashell 2>/dev/null || true; pkill -u vessel -x kwin_wayland 2>/dev/null || true", 5)
            }
        }
        useGuestAgent = false
        VesselGuestAgent.resetConnection()
        synchronized(consoleLock) {
            pendingFuture?.completeExceptionally(IllegalStateException("Vessel stopped"))
            pendingFuture = null
            pendingMarker = null
            pendingLineObserver = null
            pendingOutput.setLength(0)
        }
        runCatching {
            if (umlProcess?.isAlive == true) {
                consoleWriter?.write("exit\n")
                consoleWriter?.flush()
                umlProcess?.waitFor(8, TimeUnit.SECONDS)
            }
        }
        runCatching { consoleWriter?.close() }
        runCatching { if (umlProcess?.isAlive == true) umlProcess?.destroyForcibly() }
        runCatching { if (gpuProcess?.isAlive == true) gpuProcess?.destroyForcibly() }
        umlProcess = null
        gpuProcess = null
        consoleWriter = null
        running = false
        guestReady = false
        inputReady = false
        desktopReady = false
        stopInputBackends()
        gpuSocket.delete()
        killStaleNativeRuntimeProcesses("stop")
    }

    suspend fun stop(): JSONObject = withContext(Dispatchers.IO) {
        stopBlocking()
        VesselWaylandPresenter.resetPresentationLatch()
        lastError = ""
        baseState()
    }
}
