// Vessel Vulkan Studio v6
// Offline photoreal material courtyard: real PBR maps + HDR IBL + hybrid HW ray queries.

#include <android/asset_manager.h>
#include <android/asset_manager_jni.h>
#include <jni.h>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-function"
#pragma clang diagnostic ignored "-Wmissing-field-initializers"
#define STB_IMAGE_IMPLEMENTATION
#include "third_party/stb_image.h"
#pragma clang diagnostic pop

#define private public
#define Java_com_example_dreamlinux_NativeCubeActivity_nativeCreate Java_com_example_dreamlinux_NativeCubeActivity_nativeCreate_v3_internal
#define Java_com_example_dreamlinux_NativeCubeActivity_nativeDestroy Java_com_example_dreamlinux_NativeCubeActivity_nativeDestroy_v3_internal
#define Java_com_example_dreamlinux_NativeCubeActivity_nativeResize Java_com_example_dreamlinux_NativeCubeActivity_nativeResize_v3_internal
#define Java_com_example_dreamlinux_NativeCubeActivity_nativeRotate Java_com_example_dreamlinux_NativeCubeActivity_nativeRotate_v3_internal
#define Java_com_example_dreamlinux_NativeCubeActivity_nativeZoom Java_com_example_dreamlinux_NativeCubeActivity_nativeZoom_v3_internal
#define Java_com_example_dreamlinux_NativeCubeActivity_nativeSetStress Java_com_example_dreamlinux_NativeCubeActivity_nativeSetStress_v3_internal
#define Java_com_example_dreamlinux_NativeCubeActivity_nativeSetPhysics Java_com_example_dreamlinux_NativeCubeActivity_nativeSetPhysics_v3_internal
#define Java_com_example_dreamlinux_NativeCubeActivity_nativeSetRt Java_com_example_dreamlinux_NativeCubeActivity_nativeSetRt_v3_internal
#define Java_com_example_dreamlinux_NativeCubeActivity_nativeSetQuality Java_com_example_dreamlinux_NativeCubeActivity_nativeSetQuality_v3_internal
#define Java_com_example_dreamlinux_NativeCubeActivity_nativeResetPhysics Java_com_example_dreamlinux_NativeCubeActivity_nativeResetPhysics_v3_internal
#define Java_com_example_dreamlinux_NativeCubeActivity_nativeGrabStart Java_com_example_dreamlinux_NativeCubeActivity_nativeGrabStart_v3_internal
#define Java_com_example_dreamlinux_NativeCubeActivity_nativeGrabMove Java_com_example_dreamlinux_NativeCubeActivity_nativeGrabMove_v3_internal
#define Java_com_example_dreamlinux_NativeCubeActivity_nativeGrabEnd Java_com_example_dreamlinux_NativeCubeActivity_nativeGrabEnd_v3_internal
#define Java_com_example_dreamlinux_NativeCubeActivity_nativeStatus Java_com_example_dreamlinux_NativeCubeActivity_nativeStatus_v3_internal
#define Java_com_example_dreamlinux_NativeCubeActivity_nativeLogs Java_com_example_dreamlinux_NativeCubeActivity_nativeLogs_v3_internal
#include "native_vulkan_studio_v3.cpp"
#undef Java_com_example_dreamlinux_NativeCubeActivity_nativeCreate
#undef Java_com_example_dreamlinux_NativeCubeActivity_nativeDestroy
#undef Java_com_example_dreamlinux_NativeCubeActivity_nativeResize
#undef Java_com_example_dreamlinux_NativeCubeActivity_nativeRotate
#undef Java_com_example_dreamlinux_NativeCubeActivity_nativeZoom
#undef Java_com_example_dreamlinux_NativeCubeActivity_nativeSetStress
#undef Java_com_example_dreamlinux_NativeCubeActivity_nativeSetPhysics
#undef Java_com_example_dreamlinux_NativeCubeActivity_nativeSetRt
#undef Java_com_example_dreamlinux_NativeCubeActivity_nativeSetQuality
#undef Java_com_example_dreamlinux_NativeCubeActivity_nativeResetPhysics
#undef Java_com_example_dreamlinux_NativeCubeActivity_nativeGrabStart
#undef Java_com_example_dreamlinux_NativeCubeActivity_nativeGrabMove
#undef Java_com_example_dreamlinux_NativeCubeActivity_nativeGrabEnd
#undef Java_com_example_dreamlinux_NativeCubeActivity_nativeStatus
#undef Java_com_example_dreamlinux_NativeCubeActivity_nativeLogs
#undef private

#include "native_studio_v6_vert_spv.h"
#include "native_studio_v6_frag_spv.h"
#include "native_studio_v6_rt_frag_spv.h"

namespace {
constexpr float kV6RoomHalf=6.32f;
constexpr float kV6Ceiling=4.90f;
constexpr uint32_t kV6HeroGrid=24;
constexpr uint32_t kV6HeroVerts=6u*kV6HeroGrid*kV6HeroGrid*6u;
constexpr uint32_t kV6FloorGrid=56;
constexpr uint32_t kV6FloorVerts=kV6FloorGrid*kV6FloorGrid*6u;
constexpr uint32_t kV6ArchBoxes=12;
constexpr uint32_t kV6ArchVerts=kV6ArchBoxes*36u;
constexpr uint32_t kV6StaticVerts=kV6HeroVerts+kV6FloorVerts+kV6ArchVerts;
constexpr uint32_t kV6SphereVerts=40u*20u*6u;
constexpr uint32_t kV6QualityBodies=5u;
constexpr uint32_t kV6QualityVerts=kV6StaticVerts+kV6QualityBodies*kV6SphereVerts;
constexpr uint32_t kV6StressSphereVerts=16u*8u*6u;
constexpr uint32_t kV6StaticInstances=14u;
constexpr uint32_t kV6MaxInstances=kV6StaticInstances+kBodyCount;

struct TextureV6{
    VkImage image=VK_NULL_HANDLE;
    VkDeviceMemory memory=VK_NULL_HANDLE;
    VkImageView view=VK_NULL_HANDLE;
    VkSampler sampler=VK_NULL_HANDLE;
    uint32_t width=0,height=0,mips=1;
};

class VulkanStudioV6 final:public VulkanStudioV3{
public:
    VulkanStudioV6(ANativeWindow* w,AAssetManager* assets):VulkanStudioV3(w),assets_(assets){
        if(!assets_)throw std::runtime_error("Android AssetManager unavailable");
        configureBodiesV6();cameraDistance_=7.15f;pitch_=0.16f;yaw_=-0.58f;
        logV6("Studio v6 · photoreal courtyard renderer");
        logV6("offline assets · Poly Haven CC0 PBR + HDRI");
        logV6("lighting · HDR IBL + sun + architectural lights + movable area light");
        logV6("RT · dominant-light contact shadow + wet/metal reflections + resin transmission");
    }
    void start(){bool expected=false;if(!running_.compare_exchange_strong(expected,true))return;thread_=std::thread([this]{loopV6();});}
    void zoom(float s){VulkanStudioV3::zoom(s);cameraDistance_=std::clamp(cameraDistance_.load(),4.2f,10.5f);}
    void resetPhysics(){std::lock_guard<std::mutex>lock(bodyMutex_);initBodiesLocked();configureBodiesLockedV6();grabbed_=-1;grabTargetVelocity_={};omega_.fill({});spin_.fill(0);logV6Unlocked("scene reset · courtyard physics restored");}
    void grabStart(float nx,float ny){grabStartImpl(nx,ny,false);}
    void grabLightStart(float nx,float ny){grabStartImpl(nx,ny,true);}
    void grabMove(float nx,float ny){std::lock_guard<std::mutex>lock(bodyMutex_);if(grabbed_<0)return;Vec3 ro,rd;screenRay(nx,ny,ro,rd);Vec3 next=ro+rd*grabDepth_;auto now=Clock::now();float dt=std::chrono::duration<float>(now-grabLastUpdate_).count();if(dt>.0005f){Vec3 instant=(next-grabPrevTarget_)/dt;float s=len(instant);if(s>11.5f)instant=instant*(11.5f/s);grabTargetVelocity_=grabTargetVelocity_*.80f+instant*.20f;}grabPrevTarget_=next;grabTarget_=next;grabLastUpdate_=now;if(!physics_.load()){Body&b=bodies_[grabbed_];b.p=clampInsideV6(next,b.r);b.v={};omega_[grabbed_]={};}}
    void grabEnd(){std::lock_guard<std::mutex>lock(bodyMutex_);if(grabbed_>=0&&physics_.load()){bodies_[grabbed_].v+=grabTargetVelocity_*.42f;float s=len(bodies_[grabbed_].v);if(s>12.5f)bodies_[grabbed_].v=bodies_[grabbed_].v*(12.5f/s);}grabbed_=-1;grabTargetVelocity_={};}

private:
    void logV6(const std::string&s){__android_log_print(ANDROID_LOG_INFO,kTag,"%s",s.c_str());std::lock_guard<std::mutex>lock(logMutex_);logV6Unlocked(s);}
    void logV6Unlocked(const std::string&s){logs_.push_back(s);if(logs_.size()>220)logs_.erase(logs_.begin(),logs_.begin()+static_cast<std::ptrdiff_t>(logs_.size()-220));}

    std::vector<unsigned char>assetBytes(const char*path){AAsset*a=AAssetManager_open(assets_,path,AASSET_MODE_BUFFER);if(!a)throw std::runtime_error(std::string("missing packaged asset: ")+path);off_t n=AAsset_getLength(a);std::vector<unsigned char>d(static_cast<size_t>(n));int64_t got=AAsset_read(a,d.data(),static_cast<size_t>(n));AAsset_close(a);if(got!=n)throw std::runtime_error(std::string("short asset read: ")+path);return d;}
    uint16_t f16(float f){uint32_t x;std::memcpy(&x,&f,4);uint32_t sign=(x>>16)&0x8000u;int exp=int((x>>23)&0xffu)-127+15;uint32_t mant=x&0x7fffffu;if(exp<=0){if(exp<-10)return static_cast<uint16_t>(sign);mant=(mant|0x800000u)>>(1-exp);return static_cast<uint16_t>(sign+((mant+0x1000u)>>13));}if(exp>=31)return static_cast<uint16_t>(sign|0x7c00u);return static_cast<uint16_t>(sign|(uint32_t(exp)<<10)|((mant+0x1000u)>>13));}

    TextureV6 createTexture8(const char*path,VkFormat fmt,bool clamp=false){auto bytes=assetBytes(path);int w=0,h=0,c=0;stbi_uc*p=stbi_load_from_memory(bytes.data(),static_cast<int>(bytes.size()),&w,&h,&c,STBI_rgb_alpha);if(!p)throw std::runtime_error(std::string("stb decode failed: ")+path);TextureV6 t=createTextureRaw(p,static_cast<size_t>(w)*static_cast<size_t>(h)*4u,w,h,fmt,clamp);stbi_image_free(p);return t;}
    TextureV6 createTextureHdr(const char*path){auto bytes=assetBytes(path);int w=0,h=0,c=0;float*p=stbi_loadf_from_memory(bytes.data(),static_cast<int>(bytes.size()),&w,&h,&c,STBI_rgb_alpha);if(!p)throw std::runtime_error(std::string("HDR decode failed: ")+path);std::vector<uint16_t>half(static_cast<size_t>(w)*static_cast<size_t>(h)*4u);for(size_t i=0;i<half.size();++i)half[i]=f16(std::clamp(p[i],0.0f,65504.0f));stbi_image_free(p);return createTextureRaw(half.data(),half.size()*sizeof(uint16_t),w,h,VK_FORMAT_R16G16B16A16_SFLOAT,true);}

    TextureV6 createTextureRaw(const void*pixels,size_t bytes,int w,int h,VkFormat fmt,bool clamp){
        TextureV6 t{};t.width=static_cast<uint32_t>(w);t.height=static_cast<uint32_t>(h);t.mips=1u+static_cast<uint32_t>(std::floor(std::log2(double(std::max(w,h)))));
        Buffer staging=createBuffer(bytes,VK_BUFFER_USAGE_TRANSFER_SRC_BIT,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,false);std::memcpy(staging.mapped,pixels,bytes);
        VkImageCreateInfo ii{VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO};ii.imageType=VK_IMAGE_TYPE_2D;ii.extent={t.width,t.height,1};ii.mipLevels=t.mips;ii.arrayLayers=1;ii.format=fmt;ii.tiling=VK_IMAGE_TILING_OPTIMAL;ii.initialLayout=VK_IMAGE_LAYOUT_UNDEFINED;ii.usage=VK_IMAGE_USAGE_TRANSFER_DST_BIT|VK_IMAGE_USAGE_TRANSFER_SRC_BIT|VK_IMAGE_USAGE_SAMPLED_BIT;ii.samples=VK_SAMPLE_COUNT_1_BIT;ii.sharingMode=VK_SHARING_MODE_EXCLUSIVE;checkVk(vkCreateImage(device_,&ii,nullptr,&t.image),"v6 texture image");
        VkMemoryRequirements mr{};vkGetImageMemoryRequirements(device_,t.image,&mr);VkMemoryAllocateInfo ai{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};ai.allocationSize=mr.size;ai.memoryTypeIndex=memType(mr.memoryTypeBits,VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);checkVk(vkAllocateMemory(device_,&ai,nullptr,&t.memory),"v6 texture memory");checkVk(vkBindImageMemory(device_,t.image,t.memory,0),"v6 texture bind");
        VkCommandBuffer cmd=beginOne();VkImageMemoryBarrier b{VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};b.oldLayout=VK_IMAGE_LAYOUT_UNDEFINED;b.newLayout=VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;b.srcQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED;b.dstQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED;b.image=t.image;b.subresourceRange.aspectMask=VK_IMAGE_ASPECT_COLOR_BIT;b.subresourceRange.levelCount=t.mips;b.subresourceRange.layerCount=1;b.dstAccessMask=VK_ACCESS_TRANSFER_WRITE_BIT;vkCmdPipelineBarrier(cmd,VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,VK_PIPELINE_STAGE_TRANSFER_BIT,0,0,nullptr,0,nullptr,1,&b);
        VkBufferImageCopy region{};region.imageSubresource.aspectMask=VK_IMAGE_ASPECT_COLOR_BIT;region.imageSubresource.layerCount=1;region.imageExtent={t.width,t.height,1};vkCmdCopyBufferToImage(cmd,staging.buffer,t.image,VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,1,&region);
        int32_t mw=w,mh=h;for(uint32_t level=1;level<t.mips;++level){VkImageMemoryBarrier prev{VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};prev.image=t.image;prev.srcQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED;prev.dstQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED;prev.subresourceRange.aspectMask=VK_IMAGE_ASPECT_COLOR_BIT;prev.subresourceRange.baseMipLevel=level-1;prev.subresourceRange.levelCount=1;prev.subresourceRange.layerCount=1;prev.oldLayout=VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;prev.newLayout=VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;prev.srcAccessMask=VK_ACCESS_TRANSFER_WRITE_BIT;prev.dstAccessMask=VK_ACCESS_TRANSFER_READ_BIT;vkCmdPipelineBarrier(cmd,VK_PIPELINE_STAGE_TRANSFER_BIT,VK_PIPELINE_STAGE_TRANSFER_BIT,0,0,nullptr,0,nullptr,1,&prev);VkImageBlit bl{};bl.srcSubresource.aspectMask=VK_IMAGE_ASPECT_COLOR_BIT;bl.srcSubresource.mipLevel=level-1;bl.srcSubresource.layerCount=1;bl.srcOffsets[1]={mw,mh,1};bl.dstSubresource.aspectMask=VK_IMAGE_ASPECT_COLOR_BIT;bl.dstSubresource.mipLevel=level;bl.dstSubresource.layerCount=1;bl.dstOffsets[1]={std::max(1,mw/2),std::max(1,mh/2),1};vkCmdBlitImage(cmd,t.image,VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,t.image,VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,1,&bl,VK_FILTER_LINEAR);VkImageMemoryBarrier done=prev;done.oldLayout=VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;done.newLayout=VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;done.srcAccessMask=VK_ACCESS_TRANSFER_READ_BIT;done.dstAccessMask=VK_ACCESS_SHADER_READ_BIT;vkCmdPipelineBarrier(cmd,VK_PIPELINE_STAGE_TRANSFER_BIT,VK_PIPELINE_STAGE_VERTEX_SHADER_BIT|VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,0,0,nullptr,0,nullptr,1,&done);mw=std::max(1,mw/2);mh=std::max(1,mh/2);}
        VkImageMemoryBarrier last{VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};last.image=t.image;last.srcQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED;last.dstQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED;last.subresourceRange.aspectMask=VK_IMAGE_ASPECT_COLOR_BIT;last.subresourceRange.baseMipLevel=t.mips-1;last.subresourceRange.levelCount=1;last.subresourceRange.layerCount=1;last.oldLayout=VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;last.newLayout=VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;last.srcAccessMask=VK_ACCESS_TRANSFER_WRITE_BIT;last.dstAccessMask=VK_ACCESS_SHADER_READ_BIT;vkCmdPipelineBarrier(cmd,VK_PIPELINE_STAGE_TRANSFER_BIT,VK_PIPELINE_STAGE_VERTEX_SHADER_BIT|VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,0,0,nullptr,0,nullptr,1,&last);endOne(cmd);destroyBuffer(staging);
        VkImageViewCreateInfo vi{VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};vi.image=t.image;vi.viewType=VK_IMAGE_VIEW_TYPE_2D;vi.format=fmt;vi.subresourceRange.aspectMask=VK_IMAGE_ASPECT_COLOR_BIT;vi.subresourceRange.levelCount=t.mips;vi.subresourceRange.layerCount=1;checkVk(vkCreateImageView(device_,&vi,nullptr,&t.view),"v6 texture view");VkSamplerCreateInfo si{VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO};si.magFilter=VK_FILTER_LINEAR;si.minFilter=VK_FILTER_LINEAR;si.mipmapMode=VK_SAMPLER_MIPMAP_MODE_LINEAR;si.addressModeU=clamp?VK_SAMPLER_ADDRESS_MODE_REPEAT:VK_SAMPLER_ADDRESS_MODE_REPEAT;si.addressModeV=clamp?VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE:VK_SAMPLER_ADDRESS_MODE_REPEAT;si.addressModeW=VK_SAMPLER_ADDRESS_MODE_REPEAT;si.minLod=0;si.maxLod=float(t.mips-1);si.maxAnisotropy=1;checkVk(vkCreateSampler(device_,&si,nullptr,&t.sampler),"v6 texture sampler");return t;
    }
    void destroyTexture(TextureV6&t){if(!device_)return;if(t.sampler)vkDestroySampler(device_,t.sampler,nullptr);if(t.view)vkDestroyImageView(device_,t.view,nullptr);if(t.image)vkDestroyImage(device_,t.image,nullptr);if(t.memory)vkFreeMemory(device_,t.memory,nullptr);t={};}
    void loadTexturesV6(){floorAlb_=createTexture8("vulkan_v6/slab_tiles_diff_2k.jpg",VK_FORMAT_R8G8B8A8_SRGB);floorNormal_=createTexture8("vulkan_v6/slab_tiles_nor_gl_2k.jpg",VK_FORMAT_R8G8B8A8_UNORM);floorArm_=createTexture8("vulkan_v6/slab_tiles_arm_2k.jpg",VK_FORMAT_R8G8B8A8_UNORM);floorHeight_=createTexture8("vulkan_v6/slab_tiles_disp_2k.png",VK_FORMAT_R8G8B8A8_UNORM);concreteAlb_=createTexture8("vulkan_v6/rough_concrete_diff_2k.jpg",VK_FORMAT_R8G8B8A8_SRGB);concreteNormal_=createTexture8("vulkan_v6/rough_concrete_nor_gl_2k.jpg",VK_FORMAT_R8G8B8A8_UNORM);concreteArm_=createTexture8("vulkan_v6/rough_concrete_arm_2k.jpg",VK_FORMAT_R8G8B8A8_UNORM);concreteHeight_=createTexture8("vulkan_v6/rough_concrete_disp_2k.png",VK_FORMAT_R8G8B8A8_UNORM);environment_=createTextureHdr("vulkan_v6/evening_museum_courtyard_1k.hdr");logV6("PBR assets loaded · slab tile + rough concrete + 1K HDR environment");}

    std::vector<Vec3>roundedCubeTrianglesV6(){std::vector<Vec3>v;v.reserve(kV6HeroVerts);auto facePoint=[](int face,float u,float vv){Vec3 unit;float a=u*2-1,b=vv*2-1;if(face==0)unit={a,b,1};else if(face==1)unit={-a,b,-1};else if(face==2)unit={1,b,-a};else if(face==3)unit={-1,b,a};else if(face==4)unit={a,1,-b};else unit={a,-1,b};Vec3 he{1.18f,1.02f,1.18f},in{1.075f,.915f,1.075f};Vec3 raw{unit.x*he.x,unit.y*he.y,unit.z*he.z};Vec3 c{std::clamp(raw.x,-in.x,in.x),std::clamp(raw.y,-in.y,in.y),std::clamp(raw.z,-in.z,in.z)};Vec3 d=raw-c;return c+norm(d)*.105f;};for(int f=0;f<6;++f)for(uint32_t y=0;y<kV6HeroGrid;++y)for(uint32_t x=0;x<kV6HeroGrid;++x){float u0=float(x)/kV6HeroGrid,u1=float(x+1)/kV6HeroGrid,v0=float(y)/kV6HeroGrid,v1=float(y+1)/kV6HeroGrid;Vec3 a=facePoint(f,u0,v0),b=facePoint(f,u1,v0),c=facePoint(f,u1,v1),d=facePoint(f,u0,v1);v.insert(v.end(),{a,b,c,a,c,d});}return v;}

    int activeBodiesV6()const{if(!stress_.load())return static_cast<int>(kV6QualityBodies);int extras=std::clamp(10+(quality_.load()*30)/100,10,40);return static_cast<int>(kV6QualityBodies)+extras;}
    void configureBodiesV6(){std::lock_guard<std::mutex>lock(bodyMutex_);configureBodiesLockedV6();}
    void configureBodiesLockedV6(){if(bodies_.size()<kV6QualityBodies)return;auto setup=[&](int i,Vec3 p,float r,int mat,float rest,float fric,float density,bool gummy=false){Body&b=bodies_[i];b.p=p;b.v={};b.r=r;b.material=mat;b.restitution=rest;b.friction=fric;b.gummy=gummy;b.deform=b.deformV=0;b.mass=std::max(.18f,4.18879f*r*r*r*density);};setup(0,{-2.15f,kFloorY+.70f,-.25f},.70f,2,.26f,.30f,6.8f);setup(1,{.60f,kFloorY+.72f,.35f},.72f,3,.62f,.25f,1.10f,true);setup(2,{-.45f,2.45f,-2.05f},.34f,4,.28f,.33f,1.0f);setup(3,{2.28f,kFloorY+.66f,-.18f},.66f,7,.32f,.34f,1.55f);setup(4,{-.55f,kFloorY+.62f,1.85f},.62f,9,.38f,.30f,1.30f);for(int i=5;i<kBodyCount;++i){int n=i-5,gx=n%8,gz=n/8;float r=.25f+.025f*float((n*7)%4);int mat=(n%7==0)?8:((n%4==0)?6:((n%3==0)?7:2));float density=mat==8?5.1f:(mat==2?5.8f:1.7f);setup(i,{(float(gx)-3.5f)*1.10f,kFloorY+r+.10f*float(n%3),(float(gz)-2.2f)*1.08f},r,mat,.28f+.04f*float(n%3),.38f,density);}omega_.fill({});spin_.fill(0);}
    Vec3 clampInsideV6(Vec3 p,float r)const{p.x=std::clamp(p.x,-kV6RoomHalf+r,kV6RoomHalf-r);p.z=std::clamp(p.z,-kV6RoomHalf+r,kV6RoomHalf-r);p.y=std::clamp(p.y,kFloorY+r,kV6Ceiling-r);return p;}

    void applyPlaneContact(Body&b,int i,Vec3 n,float pen){if(pen<=0)return;b.p+=n*pen;float invM=1.0f/std::max(.08f,b.mass),invI=1.0f/std::max(.01f,.4f*b.mass*b.r*b.r);Vec3 r=n*(-b.r),rv=b.v+cross(omega_[i],r);float vn=dot(rv,n);float jn=0;if(vn<0){jn=-(1.0f+b.restitution)*vn/invM;Vec3 J=n*jn;b.v+=J*invM;omega_[i]+=cross(r,J)*invI;}rv=b.v+cross(omega_[i],r);Vec3 tv=rv-n*dot(rv,n);float tl=len(tv);if(tl>1e-4f){Vec3 t=tv/tl;Vec3 rx=cross(r,t);float denom=invM+dot(cross(rx*invI,r),t);float jt=-dot(rv,t)/std::max(denom,.001f);jt=std::clamp(jt,-std::abs(jn)*b.friction,std::abs(jn)*b.friction);Vec3 F=t*jt;b.v+=F*invM;omega_[i]+=cross(r,F)*invI;}if(b.gummy&&std::abs(jn)>.02f)b.deformV+=std::min(1.0f,std::abs(jn)*invM*.035f);}
    void collideRoomV6(Body&b,int i){applyPlaneContact(b,i,{1,0,0},(-kV6RoomHalf+b.r)-b.p.x);applyPlaneContact(b,i,{-1,0,0},b.p.x-(kV6RoomHalf-b.r));applyPlaneContact(b,i,{0,0,1},(-kV6RoomHalf+b.r)-b.p.z);applyPlaneContact(b,i,{0,0,-1},b.p.z-(kV6RoomHalf-b.r));applyPlaneContact(b,i,{0,1,0},kFloorY-(b.p.y-b.r));applyPlaneContact(b,i,{0,-1,0},(b.p.y+b.r)-kV6Ceiling);}
    void collideHeroV6(Body&b,int i){Vec3 lo{-1.18f,-1.02f,-1.18f},hi{1.18f,1.02f,1.18f};Vec3 cp{std::clamp(b.p.x,lo.x,hi.x),std::clamp(b.p.y,lo.y,hi.y),std::clamp(b.p.z,lo.z,hi.z)};Vec3 d=b.p-cp;float dl=len(d);if(dl>=b.r)return;Vec3 n=dl>1e-5f?d/dl:norm(Vec3{b.p.x,0,b.p.z});float pen=b.r-dl;b.p+=n*pen;float invM=1/std::max(.08f,b.mass);Vec3 rv=b.v;float vn=dot(rv,n);if(vn<0)b.v-=n*((1+b.restitution)*vn);Vec3 t=b.v-n*dot(b.v,n);b.v-=t*std::min(.32f,b.friction*.24f);omega_[i]+=cross(n*(-b.r),n*std::abs(vn)*b.mass)*(.04f*invM);if(b.gummy)b.deformV+=std::abs(vn)*.08f;}
    void solvePairV6(int ia,int ib){Body&a=bodies_[ia],&b=bodies_[ib];Vec3 d=b.p-a.p;float dist=len(d),rr=a.r+b.r;if(dist>=rr||dist<1e-6f)return;Vec3 n=d/dist;float ima=1/std::max(.08f,a.mass),imb=1/std::max(.08f,b.mass),sum=ima+imb,pen=rr-dist;Vec3 corr=n*(std::max(0.f,pen-.0008f)*.68f/sum);a.p-=corr*ima;b.p+=corr*imb;Vec3 ra=n*a.r,rb=n*(-b.r);Vec3 va=a.v+cross(omega_[ia],ra),vb=b.v+cross(omega_[ib],rb),rel=vb-va;float vn=dot(rel,n);if(vn>=0)return;float e=std::min(a.restitution,b.restitution),jn=-(1+e)*vn/sum;Vec3 J=n*jn;a.v-=J*ima;b.v+=J*imb;float iia=1/std::max(.01f,.4f*a.mass*a.r*a.r),iib=1/std::max(.01f,.4f*b.mass*b.r*b.r);rel=(b.v+cross(omega_[ib],rb))-(a.v+cross(omega_[ia],ra));Vec3 tv=rel-n*dot(rel,n);float tl=len(tv);if(tl>1e-4f){Vec3 t=tv/tl;Vec3 rax=cross(ra,t),rbx=cross(rb,t);float denom=sum+dot(cross(rax*iia,ra),t)+dot(cross(rbx*iib,rb),t);float jt=-dot(rel,t)/std::max(denom,.001f);float mu=std::sqrt(std::max(0.f,a.friction*b.friction));jt=std::clamp(jt,-jn*mu,jn*mu);Vec3 F=t*jt;a.v-=F*ima;b.v+=F*imb;omega_[ia]-=cross(ra,F)*iia;omega_[ib]+=cross(rb,F)*iib;}if(a.gummy)a.deformV+=std::abs(jn)*ima*.035f;if(b.gummy)b.deformV+=std::abs(jn)*imb*.035f;}
    void physicsStepV6(float dt){std::lock_guard<std::mutex>lock(bodyMutex_);if(!physics_.load())return;int n=activeBodiesV6();const int sub=6;float h=std::min(dt,.022f)/float(sub);for(int s=0;s<sub;++s){for(int i=0;i<n;++i){Body&b=bodies_[i];b.v.y-=9.81f*h;if(i==grabbed_){Vec3 err=grabTarget_-b.p;Vec3 acc=err*54.0f+(grabTargetVelocity_-b.v)*14.0f;float al=len(acc);if(al>78)acc=acc*(78/al);b.v+=acc*h;}b.v=b.v*(1.0f-.025f*h);omega_[i]=omega_[i]*(1.0f-.15f*h);b.p+=b.v*h;collideRoomV6(b,i);collideHeroV6(b,i);spin_[i]+=len(omega_[i])*h;}for(int it=0;it<4;++it)for(int i=0;i<n;++i)for(int j=i+1;j<n;++j)solvePairV6(i,j);for(int i=0;i<n;++i){Body&b=bodies_[i];if(b.gummy){constexpr float spring=52.0f,damping=11.6f;b.deformV+=(-spring*b.deform-damping*b.deformV)*h;b.deform+=b.deformV*h;b.deform=std::clamp(b.deform,-.038f,.080f);}}}}
    void updateBodyGpuV6(){if(!bodyMapped_)return;std::lock_guard<std::mutex>lock(bodyMutex_);auto*out=reinterpret_cast<BodyGpu*>(bodyMapped_);for(int i=0;i<kBodyCount;++i){const Body&b=bodies_[i];out[i]={{b.p.x,b.p.y,b.p.z,b.r},{b.v.x,b.v.y,b.v.z,b.mass},{b.deform,spin_[i],len(omega_[i]),0},{b.material,b.gummy?1:0,0,0}};}}

    void grabStartImpl(float nx,float ny,bool forceLight){std::lock_guard<std::mutex>lock(bodyMutex_);Vec3 ro,rd;screenRay(nx,ny,ro,rd);int bestIndex=forceLight?2:-1;float best=1e9f;if(forceLight){Vec3 to=bodies_[2].p-ro;best=std::max(.4f,dot(to,rd));}else{for(int i=0;i<activeBodiesV6();++i){const Body&b=bodies_[i];float pickR=b.r*1.16f+.035f;Vec3 oc=ro-b.p;float qb=dot(oc,rd),c=dot(oc,oc)-pickR*pickR,disc=qb*qb-c;if(disc<0)continue;float t=-qb-std::sqrt(disc);if(t>.02f&&t<best){best=t;bestIndex=i;}}}grabbed_=bestIndex;grabDepth_=best;if(grabbed_>=0){grabTarget_=ro+rd*best;grabPrevTarget_=grabTarget_;grabTargetVelocity_={};grabLastUpdate_=Clock::now();logV6Unlocked(std::string("grab ")+(grabbed_==2?"MOVABLE LIGHT":grabbed_==1?"AMBER GUMMY":"body "+std::to_string(grabbed_)));}}

    void rebuildTlasV6(){if(!rtSupported_)return;vkDeviceWaitIdle(device_);destroyAccel(tlas_);destroyBuffer(tlasScratch_);destroyBuffer(instanceBuffer_);if(heroCubeAs_.handle)destroyAccel(heroCubeAs_);destroyBuffer(heroCubeGeom_);heroCubeAs_=buildBlas(roundedCubeTrianglesV6(),heroCubeGeom_);instanceBuffer_=createBuffer(sizeof(VkAccelerationStructureInstanceKHR)*kV6MaxInstances,VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_BUILD_INPUT_READ_ONLY_BIT_KHR|VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,true);VkAccelerationStructureGeometryInstancesDataKHR id{VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_GEOMETRY_INSTANCES_DATA_KHR};id.data.deviceAddress=addr(instanceBuffer_.buffer);VkAccelerationStructureGeometryKHR g{VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_GEOMETRY_KHR};g.geometryType=VK_GEOMETRY_TYPE_INSTANCES_KHR;g.geometry.instances=id;uint32_t count=kV6MaxInstances;VkAccelerationStructureBuildGeometryInfoKHR info{VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_BUILD_GEOMETRY_INFO_KHR};info.type=VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_KHR;info.flags=VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_BUILD_BIT_KHR|VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_UPDATE_BIT_KHR;info.geometryCount=1;info.pGeometries=&g;VkAccelerationStructureBuildSizesInfoKHR sz{VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_BUILD_SIZES_INFO_KHR};fpGetBuildSizes_(device_,VK_ACCELERATION_STRUCTURE_BUILD_TYPE_DEVICE_KHR,&info,&count,&sz);tlas_.storage=createBuffer(sz.accelerationStructureSize,VK_BUFFER_USAGE_ACCELERATION_STRUCTURE_STORAGE_BIT_KHR,VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT,false);VkAccelerationStructureCreateInfoKHR ci{VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_CREATE_INFO_KHR};ci.buffer=tlas_.storage.buffer;ci.size=sz.accelerationStructureSize;ci.type=VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_KHR;checkVk(fpCreateAS_(device_,&ci,nullptr,&tlas_.handle),"v6 TLAS");tlasScratch_=createBuffer(std::max(sz.buildScratchSize,sz.updateScratchSize),VK_BUFFER_USAGE_STORAGE_BUFFER_BIT|VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT,VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT,true);tlasGeometry_=g;tlasBuilt_=false;logV6("v6 TLAS · rounded hero + courtyard architecture + dynamic bodies");}
    void putInstance(VkAccelerationStructureInstanceKHR*d,uint32_t i,Vec3 p,float sx,float sy,float sz,uint32_t custom,Accel&as){d[i].transform=transform(p,sx,sy,sz);d[i].instanceCustomIndex=custom;d[i].mask=0xff;d[i].flags=VK_GEOMETRY_INSTANCE_TRIANGLE_FACING_CULL_DISABLE_BIT_KHR;d[i].accelerationStructureReference=as.address;}
    void updateInstancesV6(){auto*d=reinterpret_cast<VkAccelerationStructureInstanceKHR*>(instanceBuffer_.mapped);std::memset(d,0,sizeof(VkAccelerationStructureInstanceKHR)*kV6MaxInstances);putInstance(d,0,{0,kFloorY,0},6.55f,1,6.55f,0,floorAs_);putInstance(d,1,{0,0,0},1,1,1,1,heroCubeAs_);putInstance(d,2,{0,1.55f,-6.45f},6.45f,2.55f,.12f,2,cubeAs_);putInstance(d,3,{-6.45f,.95f,0},.12f,1.95f,6.45f,3,cubeAs_);putInstance(d,4,{6.45f,.95f,0},.12f,1.95f,6.45f,4,cubeAs_);putInstance(d,5,{-4.55f,-.34f,-4.75f},1.25f,.67f,.78f,5,cubeAs_);putInstance(d,6,{4.55f,-.34f,-4.55f},1.25f,.67f,.78f,6,cubeAs_);putInstance(d,7,{-5.05f,1.35f,-5.75f},.38f,2.35f,.38f,7,cubeAs_);putInstance(d,8,{5.05f,1.35f,-5.75f},.38f,2.35f,.38f,8,cubeAs_);putInstance(d,9,{-4.94f,1.38f,-5.34f},.055f,1.28f,.055f,9,cubeAs_);putInstance(d,10,{4.94f,1.38f,-5.34f},.055f,1.28f,.055f,10,cubeAs_);putInstance(d,11,{0,-.38f,-5.65f},2.45f,.60f,.48f,11,cubeAs_);putInstance(d,12,{-3.45f,-.62f,4.95f},.10f,.38f,.10f,12,cubeAs_);putInstance(d,13,{3.45f,-.62f,4.95f},.10f,.38f,.10f,13,cubeAs_);std::lock_guard<std::mutex>lock(bodyMutex_);int active=activeBodiesV6();for(int i=0;i<kBodyCount;++i){const Body&b=bodies_[i];auto&ins=d[kV6StaticInstances+uint32_t(i)];ins.transform=transform(b.p,b.r,b.r,b.r);ins.instanceCustomIndex=kV6StaticInstances+uint32_t(i);ins.mask=i<active?0xff:0;ins.flags=VK_GEOMETRY_INSTANCE_TRIANGLE_FACING_CULL_DISABLE_BIT_KHR;ins.accelerationStructureReference=sphereAs_.address;}}
    void cmdUpdateTlasV6(VkCommandBuffer cmd){updateInstancesV6();VkAccelerationStructureGeometryInstancesDataKHR id{VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_GEOMETRY_INSTANCES_DATA_KHR};id.data.deviceAddress=addr(instanceBuffer_.buffer);tlasGeometry_.geometry.instances=id;VkAccelerationStructureBuildGeometryInfoKHR info{VK_STRUCTURE_TYPE_ACCELERATION_STRUCTURE_BUILD_GEOMETRY_INFO_KHR};info.type=VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_KHR;info.flags=VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_BUILD_BIT_KHR|VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_UPDATE_BIT_KHR;info.mode=tlasBuilt_?VK_BUILD_ACCELERATION_STRUCTURE_MODE_UPDATE_KHR:VK_BUILD_ACCELERATION_STRUCTURE_MODE_BUILD_KHR;info.srcAccelerationStructure=tlasBuilt_?tlas_.handle:VK_NULL_HANDLE;info.dstAccelerationStructure=tlas_.handle;info.geometryCount=1;info.pGeometries=&tlasGeometry_;info.scratchData.deviceAddress=addr(tlasScratch_.buffer);VkAccelerationStructureBuildRangeInfoKHR range{};range.primitiveCount=kV6StaticInstances+uint32_t(activeBodiesV6());const VkAccelerationStructureBuildRangeInfoKHR*pr=&range;fpCmdBuildAS_(cmd,1,&info,&pr);tlasBuilt_=true;VkMemoryBarrier barrier{VK_STRUCTURE_TYPE_MEMORY_BARRIER};barrier.srcAccessMask=VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_KHR;barrier.dstAccessMask=VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_KHR;vkCmdPipelineBarrier(cmd,VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR,VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,0,1,&barrier,0,nullptr,0,nullptr);}

    void rebuildDescriptorsV6(){if(pipeline_){vkDestroyPipeline(device_,pipeline_,nullptr);pipeline_=VK_NULL_HANDLE;}if(layout_){vkDestroyPipelineLayout(device_,layout_,nullptr);layout_=VK_NULL_HANDLE;}if(descPool_){vkDestroyDescriptorPool(device_,descPool_,nullptr);descPool_=VK_NULL_HANDLE;}if(descLayout_){vkDestroyDescriptorSetLayout(device_,descLayout_,nullptr);descLayout_=VK_NULL_HANDLE;}
        std::vector<VkDescriptorSetLayoutBinding>b;VkDescriptorSetLayoutBinding sb{};sb.binding=0;sb.descriptorType=VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;sb.descriptorCount=1;sb.stageFlags=VK_SHADER_STAGE_VERTEX_BIT|VK_SHADER_STAGE_FRAGMENT_BIT;b.push_back(sb);if(rtSupported_){VkDescriptorSetLayoutBinding ab{};ab.binding=1;ab.descriptorType=VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR;ab.descriptorCount=1;ab.stageFlags=VK_SHADER_STAGE_FRAGMENT_BIT;b.push_back(ab);}for(uint32_t binding=2;binding<=10;++binding){VkDescriptorSetLayoutBinding tb{};tb.binding=binding;tb.descriptorType=VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;tb.descriptorCount=1;tb.stageFlags=VK_SHADER_STAGE_VERTEX_BIT|VK_SHADER_STAGE_FRAGMENT_BIT;b.push_back(tb);}VkDescriptorSetLayoutCreateInfo li{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};li.bindingCount=uint32_t(b.size());li.pBindings=b.data();checkVk(vkCreateDescriptorSetLayout(device_,&li,nullptr,&descLayout_),"v6 descriptor layout");std::vector<VkDescriptorPoolSize>ps{{VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,1},{VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,9}};if(rtSupported_)ps.push_back({VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR,1});VkDescriptorPoolCreateInfo dpi{VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};dpi.maxSets=1;dpi.poolSizeCount=uint32_t(ps.size());dpi.pPoolSizes=ps.data();checkVk(vkCreateDescriptorPool(device_,&dpi,nullptr,&descPool_),"v6 descriptor pool");VkDescriptorSetAllocateInfo dai{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};dai.descriptorPool=descPool_;dai.descriptorSetCount=1;dai.pSetLayouts=&descLayout_;checkVk(vkAllocateDescriptorSets(device_,&dai,&descSet_),"v6 descriptor set");
        VkDescriptorBufferInfo db{bodyBuffer_.buffer,0,bodyBuffer_.size};std::vector<VkWriteDescriptorSet>w;w.reserve(11);VkWriteDescriptorSet wb{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};wb.dstSet=descSet_;wb.dstBinding=0;wb.descriptorCount=1;wb.descriptorType=VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;wb.pBufferInfo=&db;w.push_back(wb);VkWriteDescriptorSetAccelerationStructureKHR asi{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET_ACCELERATION_STRUCTURE_KHR};VkWriteDescriptorSet wa{VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};if(rtSupported_){asi.accelerationStructureCount=1;asi.pAccelerationStructures=&tlas_.handle;wa.sType=VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;wa.pNext=&asi;wa.dstSet=descSet_;wa.dstBinding=1;wa.descriptorCount=1;wa.descriptorType=VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR;w.push_back(wa);}std::array<TextureV6*,9>tex{&floorAlb_,&floorNormal_,&floorArm_,&floorHeight_,&concreteAlb_,&concreteNormal_,&concreteArm_,&concreteHeight_,&environment_};std::array<VkDescriptorImageInfo,9>infos{};std::array<VkWriteDescriptorSet,9>tw{};for(size_t i=0;i<tex.size();++i){infos[i].sampler=tex[i]->sampler;infos[i].imageView=tex[i]->view;infos[i].imageLayout=VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;tw[i].sType=VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;tw[i].dstSet=descSet_;tw[i].dstBinding=uint32_t(i)+2;tw[i].descriptorCount=1;tw[i].descriptorType=VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;tw[i].pImageInfo=&infos[i];w.push_back(tw[i]);}vkUpdateDescriptorSets(device_,uint32_t(w.size()),w.data(),0,nullptr);VkPushConstantRange pr{};pr.stageFlags=VK_SHADER_STAGE_VERTEX_BIT|VK_SHADER_STAGE_FRAGMENT_BIT;pr.size=sizeof(PushConstants);VkPipelineLayoutCreateInfo pli{VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};pli.setLayoutCount=1;pli.pSetLayouts=&descLayout_;pli.pushConstantRangeCount=1;pli.pPushConstantRanges=&pr;checkVk(vkCreatePipelineLayout(device_,&pli,nullptr,&layout_),"v6 pipeline layout");}

    void replacePipelineV6(){if(pipeline_){vkDestroyPipeline(device_,pipeline_,nullptr);pipeline_=VK_NULL_HANDLE;}VkShaderModule vs=shader(native_studio_v6_vert_spv,native_studio_v6_vert_spv_size),fs=rtSupported_?shader(native_studio_v6_rt_frag_spv,native_studio_v6_rt_frag_spv_size):shader(native_studio_v6_frag_spv,native_studio_v6_frag_spv_size);VkPipelineShaderStageCreateInfo ss[2]={{VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO},{VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO}};ss[0].stage=VK_SHADER_STAGE_VERTEX_BIT;ss[0].module=vs;ss[0].pName="main";ss[1].stage=VK_SHADER_STAGE_FRAGMENT_BIT;ss[1].module=fs;ss[1].pName="main";VkPipelineVertexInputStateCreateInfo vin{VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO};VkPipelineInputAssemblyStateCreateInfo ia{VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO};ia.topology=VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST;VkPipelineViewportStateCreateInfo vp{VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO};vp.viewportCount=1;vp.scissorCount=1;VkDynamicState ds[]={VK_DYNAMIC_STATE_VIEWPORT,VK_DYNAMIC_STATE_SCISSOR};VkPipelineDynamicStateCreateInfo dy{VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO};dy.dynamicStateCount=2;dy.pDynamicStates=ds;VkPipelineRasterizationStateCreateInfo ra{VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO};ra.polygonMode=VK_POLYGON_MODE_FILL;ra.cullMode=VK_CULL_MODE_NONE;ra.frontFace=VK_FRONT_FACE_COUNTER_CLOCKWISE;ra.lineWidth=1;VkPipelineMultisampleStateCreateInfo ms{VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO};ms.rasterizationSamples=VK_SAMPLE_COUNT_1_BIT;VkPipelineDepthStencilStateCreateInfo dep{VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO};dep.depthTestEnable=VK_TRUE;dep.depthWriteEnable=VK_TRUE;dep.depthCompareOp=VK_COMPARE_OP_LESS;VkPipelineColorBlendAttachmentState ba{};ba.colorWriteMask=0xf;VkPipelineColorBlendStateCreateInfo bl{VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO};bl.attachmentCount=1;bl.pAttachments=&ba;VkGraphicsPipelineCreateInfo gi{VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO};gi.stageCount=2;gi.pStages=ss;gi.pVertexInputState=&vin;gi.pInputAssemblyState=&ia;gi.pViewportState=&vp;gi.pRasterizationState=&ra;gi.pMultisampleState=&ms;gi.pDepthStencilState=&dep;gi.pColorBlendState=&bl;gi.pDynamicState=&dy;gi.layout=layout_;gi.renderPass=renderPass_;checkVk(vkCreateGraphicsPipelines(device_,VK_NULL_HANDLE,1,&gi,nullptr,&pipeline_),"v6 pipeline");vkDestroyShaderModule(device_,vs,nullptr);vkDestroyShaderModule(device_,fs,nullptr);logV6(rtSupported_?"v6 photoreal hybrid ray-query pipeline ready":"v6 textured HDR PBR raster pipeline ready");}
    uint32_t drawVertsV6()const{if(!stress_.load())return kV6QualityVerts;int extras=activeBodiesV6()-static_cast<int>(kV6QualityBodies);return kV6QualityVerts+uint32_t(std::max(0,extras))*kV6StressSphereVerts;}
    void recordV6(uint32_t idx,float time){VkCommandBufferBeginInfo bi{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};checkVk(vkBeginCommandBuffer(cmd_,&bi),"begin v6 cmd");if(timestamps_){vkCmdResetQueryPool(cmd_,queryPool_,0,2);vkCmdWriteTimestamp(cmd_,VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,queryPool_,0);}bool useRt=rtSupported_&&requestedRt_.load()&&quality_.load()>=42;if(useRt)cmdUpdateTlasV6(cmd_);VkClearValue cv[2]{};cv[0].color={{.035f,.045f,.055f,1}};cv[1].depthStencil={1,0};VkRenderPassBeginInfo ri{VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO};ri.renderPass=renderPass_;ri.framebuffer=fbs_[idx];ri.renderArea.extent=extent_;ri.clearValueCount=2;ri.pClearValues=cv;vkCmdBeginRenderPass(cmd_,&ri,VK_SUBPASS_CONTENTS_INLINE);vkCmdBindPipeline(cmd_,VK_PIPELINE_BIND_POINT_GRAPHICS,pipeline_);vkCmdBindDescriptorSets(cmd_,VK_PIPELINE_BIND_POINT_GRAPHICS,layout_,0,1,&descSet_,0,nullptr);VkViewport vp{};vp.width=float(extent_.width);vp.height=float(extent_.height);vp.maxDepth=1;VkRect2D sc{};sc.extent=extent_;vkCmdSetViewport(cmd_,0,1,&vp);vkCmdSetScissor(cmd_,0,1,&sc);PushConstants p{yaw_.load(),pitch_.load(),float(std::max(1,visibleW_.load()))/float(std::max(1,visibleH_.load())),cameraDistance_.load(),rotCode(preTransform_),float(quality_.load()),useRt?1.f:0.f,time};vkCmdPushConstants(cmd_,layout_,VK_SHADER_STAGE_VERTEX_BIT|VK_SHADER_STAGE_FRAGMENT_BIT,0,sizeof(p),&p);vkCmdDraw(cmd_,drawVertsV6(),1,0,0);vkCmdEndRenderPass(cmd_);if(timestamps_)vkCmdWriteTimestamp(cmd_,VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT,queryPool_,1);checkVk(vkEndCommandBuffer(cmd_),"end v6 cmd");}
    void recreateV6(){recreateSwapchain();replacePipelineV6();}
    void drawV6(float time){checkVk(vkWaitForFences(device_,1,&fence_,VK_TRUE,UINT64_MAX),"wait v6 fence");if(timestamps_&&queryIssued_){uint64_t q[2]{};if(vkGetQueryPoolResults(device_,queryPool_,0,2,sizeof(q),q,sizeof(uint64_t),VK_QUERY_RESULT_64_BIT)==VK_SUCCESS)gpuMs_=double(q[1]-q[0])*double(timestampPeriod_)/1e6;}uint32_t idx=0;VkResult a=vkAcquireNextImageKHR(device_,swap_,UINT64_MAX,imageAvail_,VK_NULL_HANDLE,&idx);if(a==VK_ERROR_OUT_OF_DATE_KHR){recreateV6();return;}if(a!=VK_SUCCESS&&a!=VK_SUBOPTIMAL_KHR)checkVk(a,"v6 acquire");checkVk(vkResetFences(device_,1,&fence_),"reset v6 fence");checkVk(vkResetCommandBuffer(cmd_,0),"reset v6 cmd");recordV6(idx,time);queryIssued_=true;VkPipelineStageFlags stage=VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;VkSubmitInfo si{VK_STRUCTURE_TYPE_SUBMIT_INFO};si.waitSemaphoreCount=1;si.pWaitSemaphores=&imageAvail_;si.pWaitDstStageMask=&stage;si.commandBufferCount=1;si.pCommandBuffers=&cmd_;si.signalSemaphoreCount=1;si.pSignalSemaphores=&renderDone_;checkVk(vkQueueSubmit(queue_,1,&si,fence_),"v6 submit");VkPresentInfoKHR pi{VK_STRUCTURE_TYPE_PRESENT_INFO_KHR};pi.waitSemaphoreCount=1;pi.pWaitSemaphores=&renderDone_;pi.swapchainCount=1;pi.pSwapchains=&swap_;pi.pImageIndices=&idx;VkResult pr=vkQueuePresentKHR(queue_,&pi);if(pr==VK_ERROR_OUT_OF_DATE_KHR||pr==VK_SUBOPTIMAL_KHR||resize_.load())recreateV6();else if(pr!=VK_SUCCESS)checkVk(pr,"v6 present");}

    void cleanupV6(){if(!device_)return;vkDeviceWaitIdle(device_);destroyTexture(floorAlb_);destroyTexture(floorNormal_);destroyTexture(floorArm_);destroyTexture(floorHeight_);destroyTexture(concreteAlb_);destroyTexture(concreteNormal_);destroyTexture(concreteArm_);destroyTexture(concreteHeight_);destroyTexture(environment_);destroyAccel(heroCubeAs_);destroyBuffer(heroCubeGeom_);}
    void loopV6(){try{setStatus("Vulkan Studio v6 · loading photoreal offline assets…");initVulkan();loadTexturesV6();if(rtSupported_)rebuildTlasV6();rebuildDescriptorsV6();replacePipelineV6();logV6("courtyard ready · textured wet paving · rounded concrete hero · HDR environment");auto last=Clock::now(),stat=last,start=last,telemetry=last;uint32_t frames=0;while(running_){auto now=Clock::now();float dt=std::chrono::duration<float>(now-last).count();last=now;physicsStepV6(dt);updateBodyGpuV6();float t=std::chrono::duration<float>(now-start).count();drawV6(t);++frames;float e=std::chrono::duration<float>(now-stat).count();if(e>=.5f){float fps=frames/e;bool rt=rtSupported_&&requestedRt_.load()&&quality_.load()>=42;std::ostringstream o;o.setf(std::ios::fixed);o.precision(1);o<<"Vulkan Studio v6 · "<<gpuName_<<" · "<<fps<<" FPS · GPU "<<gpuMs_<<" ms\n";o<<"Q"<<quality_.load()<<" · "<<(stress_.load()?"STRESS":"COURTYARD")<<" · Physics "<<(physics_.load()?"ON":"OFF")<<" · RT "<<(rt?"HYBRID HW":"OFF")<<"\n";o<<"PBR maps + HDR IBL · bodies "<<activeBodiesV6()<<" · wet reflections · resin transmission";setStatus(o.str());frames=0;stat=now;}if(std::chrono::duration<float>(now-telemetry).count()>=2.0f){std::ostringstream l;l.setf(std::ios::fixed);l.precision(2);l<<"telemetry · GPU "<<gpuMs_<<" ms · bodies "<<activeBodiesV6()<<" · HWRT "<<((rtSupported_&&requestedRt_.load())?"on":"off")<<" · 120Hz budget 8.33ms";logV6(l.str());telemetry=now;}}}catch(const std::exception&e){setStatus(std::string("ERROR: Vulkan Studio v6: ")+e.what());logV6(std::string("ERROR: ")+e.what());}cleanupV6();cleanup();}

    AAssetManager*assets_=nullptr;
    TextureV6 floorAlb_{},floorNormal_{},floorArm_{},floorHeight_{},concreteAlb_{},concreteNormal_{},concreteArm_{},concreteHeight_{},environment_{};
    Accel heroCubeAs_{};Buffer heroCubeGeom_{};
    std::array<Vec3,kBodyCount>omega_{};std::array<float,kBodyCount>spin_{};
    Vec3 grabPrevTarget_{},grabTargetVelocity_{};Clock::time_point grabLastUpdate_=Clock::now();
};

VulkanStudioV6*ptrV6(jlong h){return reinterpret_cast<VulkanStudioV6*>(static_cast<intptr_t>(h));}
}

extern "C" JNIEXPORT jlong JNICALL Java_com_example_dreamlinux_NativeCubeActivity_nativeCreate(JNIEnv*e,jobject thiz,jobject surface){ANativeWindow*w=ANativeWindow_fromSurface(e,surface);if(!w)return 0;jclass cls=e->GetObjectClass(thiz);jmethodID mid=e->GetMethodID(cls,"getAssets","()Landroid/content/res/AssetManager;");jobject amObj=e->CallObjectMethod(thiz,mid);AAssetManager*assets=AAssetManager_fromJava(e,amObj);e->DeleteLocalRef(amObj);e->DeleteLocalRef(cls);try{auto*r=new VulkanStudioV6(w,assets);r->start();return static_cast<jlong>(reinterpret_cast<intptr_t>(r));}catch(...){ANativeWindow_release(w);return 0;}}
extern "C" JNIEXPORT void JNICALL Java_com_example_dreamlinux_NativeCubeActivity_nativeDestroy(JNIEnv*,jobject,jlong h){delete ptrV6(h);}
extern "C" JNIEXPORT void JNICALL Java_com_example_dreamlinux_NativeCubeActivity_nativeResize(JNIEnv*,jobject,jlong h,jint w,jint he){if(auto*r=ptrV6(h))r->resize(w,he);}
extern "C" JNIEXPORT void JNICALL Java_com_example_dreamlinux_NativeCubeActivity_nativeRotate(JNIEnv*,jobject,jlong h,jfloat y,jfloat p){if(auto*r=ptrV6(h))r->rotate(y,p);}
extern "C" JNIEXPORT void JNICALL Java_com_example_dreamlinux_NativeCubeActivity_nativeZoom(JNIEnv*,jobject,jlong h,jfloat s){if(auto*r=ptrV6(h))r->zoom(s);}
extern "C" JNIEXPORT void JNICALL Java_com_example_dreamlinux_NativeCubeActivity_nativeSetStress(JNIEnv*,jobject,jlong h,jboolean v){if(auto*r=ptrV6(h))r->setStress(v);}
extern "C" JNIEXPORT void JNICALL Java_com_example_dreamlinux_NativeCubeActivity_nativeSetPhysics(JNIEnv*,jobject,jlong h,jboolean v){if(auto*r=ptrV6(h))r->setPhysics(v);}
extern "C" JNIEXPORT void JNICALL Java_com_example_dreamlinux_NativeCubeActivity_nativeSetRt(JNIEnv*,jobject,jlong h,jboolean v){if(auto*r=ptrV6(h))r->setRt(v);}
extern "C" JNIEXPORT void JNICALL Java_com_example_dreamlinux_NativeCubeActivity_nativeSetQuality(JNIEnv*,jobject,jlong h,jint q){if(auto*r=ptrV6(h))r->setQuality(q);}
extern "C" JNIEXPORT void JNICALL Java_com_example_dreamlinux_NativeCubeActivity_nativeResetPhysics(JNIEnv*,jobject,jlong h){if(auto*r=ptrV6(h))r->resetPhysics();}
extern "C" JNIEXPORT void JNICALL Java_com_example_dreamlinux_NativeCubeActivity_nativeGrabStart(JNIEnv*,jobject,jlong h,jfloat x,jfloat y){if(auto*r=ptrV6(h))r->grabStart(x,y);}
extern "C" JNIEXPORT void JNICALL Java_com_example_dreamlinux_NativeCubeActivity_nativeGrabLightStart(JNIEnv*,jobject,jlong h,jfloat x,jfloat y){if(auto*r=ptrV6(h))r->grabLightStart(x,y);}
extern "C" JNIEXPORT void JNICALL Java_com_example_dreamlinux_NativeCubeActivity_nativeGrabMove(JNIEnv*,jobject,jlong h,jfloat x,jfloat y){if(auto*r=ptrV6(h))r->grabMove(x,y);}
extern "C" JNIEXPORT void JNICALL Java_com_example_dreamlinux_NativeCubeActivity_nativeGrabEnd(JNIEnv*,jobject,jlong h){if(auto*r=ptrV6(h))r->grabEnd();}
extern "C" JNIEXPORT jstring JNICALL Java_com_example_dreamlinux_NativeCubeActivity_nativeStatus(JNIEnv*e,jobject,jlong h){std::string s=ptrV6(h)?ptrV6(h)->status():"renderer stopped";return e->NewStringUTF(s.c_str());}
extern "C" JNIEXPORT jstring JNICALL Java_com_example_dreamlinux_NativeCubeActivity_nativeLogs(JNIEnv*e,jobject,jlong h){std::string s=ptrV6(h)?ptrV6(h)->logs():"";return e->NewStringUTF(s.c_str());}
