#include <jni.h>
#include <android/asset_manager.h>
#include <android/asset_manager_jni.h>
#include <android/log.h>
#include <android/native_window.h>
#include <android/native_window_jni.h>
#include <vulkan/vulkan.h>
#include <algorithm>
#include <array>
#include <atomic>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <mutex>
#include <stdexcept>
#include <string>
#include <thread>
#include <vector>

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-function"
#define STB_IMAGE_IMPLEMENTATION
#include "../../third_party/stb_image.h"
#pragma clang diagnostic pop

#include "bounce_vert_spv.h"
#include "bounce_frag_spv.h"
#include "../physics/BallPhysics.h"

namespace {
using Clock=std::chrono::steady_clock;
constexpr const char* TAG="BounceQuest";
constexpr uint32_t kTotalVerts=14u*36u+36u+3u*36u+48u*24u*6u+10u*20u*10u*6u+7u*14u*3u+40u*12u*6u;
void vkok(VkResult r,const char* w){if(r!=VK_SUCCESS)throw std::runtime_error(std::string(w)+" VkResult="+std::to_string(r));}

struct Texture{VkImage image{};VkDeviceMemory mem{};VkImageView view{};VkSampler sampler{};};
struct Push{float ball[4];float motion[4];float misc[4];};

class BounceRenderer{
public:
 BounceRenderer(ANativeWindow* w,AAssetManager* a):window_(w),assets_(a){if(!w||!a)throw std::runtime_error("BounceRenderer missing window/assets");ANativeWindow_acquire(w);width_=std::max(1,ANativeWindow_getWidth(w));height_=std::max(1,ANativeWindow_getHeight(w));}
 ~BounceRenderer(){stop();cleanup();if(window_)ANativeWindow_release(window_);}
 void start(){bool exp=false;if(running_.compare_exchange_strong(exp,true))thread_=std::thread([this]{run();});}
 void stop(){if(running_.exchange(false)&&thread_.joinable())thread_.join();}
 void resize(int w,int h){width_=std::max(1,w);height_=std::max(1,h);resize_=true;}
 void input(float x,float z){moveX_=std::clamp(x,-1.f,1.f);moveZ_=std::clamp(z,-1.f,1.f);}
 void jump(){jump_.store(true);}
 void dash(){dash_.store(true);}
 void pause(bool p){paused_=p;}
 void reset(){std::lock_guard<std::mutex>l(gameMutex_);physics_.reset();startTime_=Clock::now();}
 int coins(){std::lock_guard<std::mutex>l(gameMutex_);return physics_.state().coins;}
 float elapsed(){return std::chrono::duration<float>(Clock::now()-startTime_).count();}
 std::string events(){std::lock_guard<std::mutex>l(eventMutex_);std::string s;for(auto&e:events_){if(!s.empty())s+='\n';s+=e;}events_.clear();return s;}
private:
 ANativeWindow* window_{};AAssetManager*assets_{};std::thread thread_;std::atomic<bool>running_{false},resize_{false},paused_{false};std::atomic<int>width_{1},height_{1};std::atomic<float>moveX_{0},moveZ_{0};std::atomic<bool>jump_{false},dash_{false};
 bounce::BallPhysics physics_;std::mutex gameMutex_,eventMutex_;std::vector<std::string>events_;Clock::time_point startTime_=Clock::now();
 VkInstance instance_{};VkSurfaceKHR surface_{};VkPhysicalDevice physical_{};VkDevice device_{};uint32_t queueFamily_{};VkQueue queue_{};VkSwapchainKHR swap_{};VkFormat format_{};VkExtent2D extent_{};std::vector<VkImage>images_;std::vector<VkImageView>views_;VkRenderPass pass_{};VkPipelineLayout layout_{};VkPipeline pipe_{};VkDescriptorSetLayout descLayout_{};VkDescriptorPool descPool_{};VkDescriptorSet desc_{};VkCommandPool cmdPool_{};VkCommandBuffer cmd_{};std::vector<VkFramebuffer>fbs_;VkImage depth_{};VkDeviceMemory depthMem_{};VkImageView depthView_{};VkSemaphore imageAvail_{},renderDone_{};VkFence fence_{};Texture concrete_,normal_,arm_{};

 void pushEvent(std::string s){std::lock_guard<std::mutex>l(eventMutex_);events_.push_back(std::move(s));if(events_.size()>32)events_.erase(events_.begin(),events_.begin()+8);}
 uint32_t memType(uint32_t bits,VkMemoryPropertyFlags flags){VkPhysicalDeviceMemoryProperties mp{};vkGetPhysicalDeviceMemoryProperties(physical_,&mp);for(uint32_t i=0;i<mp.memoryTypeCount;i++)if((bits&(1u<<i))&&(mp.memoryTypes[i].propertyFlags&flags)==flags)return i;throw std::runtime_error("memory type");}
 void oneShot(const std::function<void(VkCommandBuffer)>&fn){VkCommandBufferAllocateInfo ai{VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};ai.commandPool=cmdPool_;ai.level=VK_COMMAND_BUFFER_LEVEL_PRIMARY;ai.commandBufferCount=1;VkCommandBuffer c{};vkok(vkAllocateCommandBuffers(device_,&ai,&c),"alloc one-shot");VkCommandBufferBeginInfo bi{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};bi.flags=VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;vkok(vkBeginCommandBuffer(c,&bi),"begin one-shot");fn(c);vkok(vkEndCommandBuffer(c),"end one-shot");VkSubmitInfo si{VK_STRUCTURE_TYPE_SUBMIT_INFO};si.commandBufferCount=1;si.pCommandBuffers=&c;vkok(vkQueueSubmit(queue_,1,&si,VK_NULL_HANDLE),"submit one-shot");vkQueueWaitIdle(queue_);vkFreeCommandBuffers(device_,cmdPool_,1,&c);}

 std::vector<unsigned char> asset(const char*path){AAsset*a=AAssetManager_open(assets_,path,AASSET_MODE_BUFFER);if(!a)throw std::runtime_error(std::string("missing asset ")+path);off_t n=AAsset_getLength(a);std::vector<unsigned char>d(size_t(n));AAsset_read(a,d.data(),n);AAsset_close(a);return d;}
 Texture loadTexture(const char*path,bool srgb){auto b=asset(path);int w=0,h=0,ch=0;stbi_uc*p=stbi_load_from_memory(b.data(),int(b.size()),&w,&h,&ch,4);if(!p)throw std::runtime_error(std::string("texture decode ")+path);VkDeviceSize bytes=VkDeviceSize(w)*h*4;VkBuffer staging{};VkDeviceMemory sm{};VkBufferCreateInfo bci{VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO};bci.size=bytes;bci.usage=VK_BUFFER_USAGE_TRANSFER_SRC_BIT;bci.sharingMode=VK_SHARING_MODE_EXCLUSIVE;vkok(vkCreateBuffer(device_,&bci,nullptr,&staging),"staging buffer");VkMemoryRequirements mr{};vkGetBufferMemoryRequirements(device_,staging,&mr);VkMemoryAllocateInfo mai{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};mai.allocationSize=mr.size;mai.memoryTypeIndex=memType(mr.memoryTypeBits,VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT|VK_MEMORY_PROPERTY_HOST_COHERENT_BIT);vkok(vkAllocateMemory(device_,&mai,nullptr,&sm),"staging memory");vkBindBufferMemory(device_,staging,sm,0);void*m=nullptr;vkMapMemory(device_,sm,0,bytes,0,&m);std::memcpy(m,p,size_t(bytes));vkUnmapMemory(device_,sm);stbi_image_free(p);
  Texture t{};VkImageCreateInfo ii{VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO};ii.imageType=VK_IMAGE_TYPE_2D;ii.extent={uint32_t(w),uint32_t(h),1};ii.mipLevels=1;ii.arrayLayers=1;ii.format=srgb?VK_FORMAT_R8G8B8A8_SRGB:VK_FORMAT_R8G8B8A8_UNORM;ii.tiling=VK_IMAGE_TILING_OPTIMAL;ii.initialLayout=VK_IMAGE_LAYOUT_UNDEFINED;ii.usage=VK_IMAGE_USAGE_TRANSFER_DST_BIT|VK_IMAGE_USAGE_SAMPLED_BIT;ii.samples=VK_SAMPLE_COUNT_1_BIT;ii.sharingMode=VK_SHARING_MODE_EXCLUSIVE;vkok(vkCreateImage(device_,&ii,nullptr,&t.image),"texture image");vkGetImageMemoryRequirements(device_,t.image,&mr);mai.allocationSize=mr.size;mai.memoryTypeIndex=memType(mr.memoryTypeBits,VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);vkok(vkAllocateMemory(device_,&mai,nullptr,&t.mem),"texture memory");vkBindImageMemory(device_,t.image,t.mem,0);
  oneShot([&](VkCommandBuffer c){VkImageMemoryBarrier bar{VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER};bar.oldLayout=VK_IMAGE_LAYOUT_UNDEFINED;bar.newLayout=VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;bar.srcQueueFamilyIndex=bar.dstQueueFamilyIndex=VK_QUEUE_FAMILY_IGNORED;bar.image=t.image;bar.subresourceRange={VK_IMAGE_ASPECT_COLOR_BIT,0,1,0,1};bar.dstAccessMask=VK_ACCESS_TRANSFER_WRITE_BIT;vkCmdPipelineBarrier(c,VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,VK_PIPELINE_STAGE_TRANSFER_BIT,0,0,nullptr,0,nullptr,1,&bar);VkBufferImageCopy cp{};cp.imageSubresource={VK_IMAGE_ASPECT_COLOR_BIT,0,0,1};cp.imageExtent={uint32_t(w),uint32_t(h),1};vkCmdCopyBufferToImage(c,staging,t.image,VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL,1,&cp);bar.oldLayout=VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL;bar.newLayout=VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL;bar.srcAccessMask=VK_ACCESS_TRANSFER_WRITE_BIT;bar.dstAccessMask=VK_ACCESS_SHADER_READ_BIT;vkCmdPipelineBarrier(c,VK_PIPELINE_STAGE_TRANSFER_BIT,VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,0,0,nullptr,0,nullptr,1,&bar);});vkDestroyBuffer(device_,staging,nullptr);vkFreeMemory(device_,sm,nullptr);
  VkImageViewCreateInfo vi{VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};vi.image=t.image;vi.viewType=VK_IMAGE_VIEW_TYPE_2D;vi.format=ii.format;vi.subresourceRange={VK_IMAGE_ASPECT_COLOR_BIT,0,1,0,1};vkok(vkCreateImageView(device_,&vi,nullptr,&t.view),"texture view");VkSamplerCreateInfo si{VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO};si.magFilter=si.minFilter=VK_FILTER_LINEAR;si.mipmapMode=VK_SAMPLER_MIPMAP_MODE_LINEAR;si.addressModeU=si.addressModeV=si.addressModeW=VK_SAMPLER_ADDRESS_MODE_REPEAT;si.maxAnisotropy=1;si.maxLod=1;vkok(vkCreateSampler(device_,&si,nullptr,&t.sampler),"sampler");return t;}

 void init(){VkApplicationInfo app{VK_STRUCTURE_TYPE_APPLICATION_INFO};app.pApplicationName="Bounce Quest";app.apiVersion=VK_API_VERSION_1_2;const char* ie[]={VK_KHR_SURFACE_EXTENSION_NAME,VK_KHR_ANDROID_SURFACE_EXTENSION_NAME};VkInstanceCreateInfo ici{VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO};ici.pApplicationInfo=&app;ici.enabledExtensionCount=2;ici.ppEnabledExtensionNames=ie;vkok(vkCreateInstance(&ici,nullptr,&instance_),"instance");VkAndroidSurfaceCreateInfoKHR sci{VK_STRUCTURE_TYPE_ANDROID_SURFACE_CREATE_INFO_KHR};sci.window=window_;vkok(vkCreateAndroidSurfaceKHR(instance_,&sci,nullptr,&surface_),"surface");uint32_t pn=0;vkEnumeratePhysicalDevices(instance_,&pn,nullptr);std::vector<VkPhysicalDevice>pd(pn);vkEnumeratePhysicalDevices(instance_,&pn,pd.data());if(pd.empty())throw std::runtime_error("no Vulkan GPU");physical_=pd[0];for(auto p:pd){VkPhysicalDeviceProperties pr{};vkGetPhysicalDeviceProperties(p,&pr);if(pr.deviceType==VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU){physical_=p;break;}}
  uint32_t qn=0;vkGetPhysicalDeviceQueueFamilyProperties(physical_,&qn,nullptr);std::vector<VkQueueFamilyProperties>qps(qn);vkGetPhysicalDeviceQueueFamilyProperties(physical_,&qn,qps.data());bool found=false;for(uint32_t i=0;i<qn;i++){VkBool32 present=0;vkGetPhysicalDeviceSurfaceSupportKHR(physical_,i,surface_,&present);if((qps[i].queueFlags&VK_QUEUE_GRAPHICS_BIT)&&present){queueFamily_=i;found=true;break;}}if(!found)throw std::runtime_error("no present queue");float qp=1;VkDeviceQueueCreateInfo qci{VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO};qci.queueFamilyIndex=queueFamily_;qci.queueCount=1;qci.pQueuePriorities=&qp;const char* de[]={VK_KHR_SWAPCHAIN_EXTENSION_NAME};VkDeviceCreateInfo dci{VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO};dci.queueCreateInfoCount=1;dci.pQueueCreateInfos=&qci;dci.enabledExtensionCount=1;dci.ppEnabledExtensionNames=de;vkok(vkCreateDevice(physical_,&dci,nullptr,&device_),"device");vkGetDeviceQueue(device_,queueFamily_,0,&queue_);VkCommandPoolCreateInfo cpi{VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO};cpi.queueFamilyIndex=queueFamily_;cpi.flags=VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;vkok(vkCreateCommandPool(device_,&cpi,nullptr,&cmdPool_),"cmd pool");
  concrete_=loadTexture("bounce/concrete_diff.jpg",true);normal_=loadTexture("bounce/concrete_normal.jpg",false);arm_=loadTexture("bounce/concrete_arm.jpg",false);createDescriptors();createSwapchain();VkCommandBufferAllocateInfo cai{VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};cai.commandPool=cmdPool_;cai.level=VK_COMMAND_BUFFER_LEVEL_PRIMARY;cai.commandBufferCount=1;vkok(vkAllocateCommandBuffers(device_,&cai,&cmd_),"cmd");VkSemaphoreCreateInfo sei{VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO};vkCreateSemaphore(device_,&sei,nullptr,&imageAvail_);vkCreateSemaphore(device_,&sei,nullptr,&renderDone_);VkFenceCreateInfo fi{VK_STRUCTURE_TYPE_FENCE_CREATE_INFO};fi.flags=VK_FENCE_CREATE_SIGNALED_BIT;vkCreateFence(device_,&fi,nullptr,&fence_);}

 void createDescriptors(){std::array<VkDescriptorSetLayoutBinding,3> b{};for(uint32_t i=0;i<3;i++){b[i].binding=i;b[i].descriptorCount=1;b[i].descriptorType=VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;b[i].stageFlags=VK_SHADER_STAGE_FRAGMENT_BIT;}VkDescriptorSetLayoutCreateInfo li{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};li.bindingCount=3;li.pBindings=b.data();vkok(vkCreateDescriptorSetLayout(device_,&li,nullptr,&descLayout_),"desc layout");VkDescriptorPoolSize ps{VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,3};VkDescriptorPoolCreateInfo pi{VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};pi.maxSets=1;pi.poolSizeCount=1;pi.pPoolSizes=&ps;vkok(vkCreateDescriptorPool(device_,&pi,nullptr,&descPool_),"desc pool");VkDescriptorSetAllocateInfo ai{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};ai.descriptorPool=descPool_;ai.descriptorSetCount=1;ai.pSetLayouts=&descLayout_;vkok(vkAllocateDescriptorSets(device_,&ai,&desc_),"desc set");Texture*ts[3]={&concrete_,&normal_,&arm_};std::array<VkDescriptorImageInfo,3> ii{};std::array<VkWriteDescriptorSet,3>w{};for(uint32_t i=0;i<3;i++){ii[i]={ts[i]->sampler,ts[i]->view,VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL};w[i]={VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET};w[i].dstSet=desc_;w[i].dstBinding=i;w[i].descriptorCount=1;w[i].descriptorType=VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;w[i].pImageInfo=&ii[i];}vkUpdateDescriptorSets(device_,3,w.data(),0,nullptr);}

 VkShaderModule shader(const unsigned char*data,size_t n){VkShaderModuleCreateInfo ci{VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO};ci.codeSize=n;ci.pCode=reinterpret_cast<const uint32_t*>(data);VkShaderModule m{};vkok(vkCreateShaderModule(device_,&ci,nullptr,&m),"shader");return m;}
 void createSwapchain(){destroySwapchain();VkSurfaceCapabilitiesKHR cap{};vkGetPhysicalDeviceSurfaceCapabilitiesKHR(physical_,surface_,&cap);uint32_t fn=0;vkGetPhysicalDeviceSurfaceFormatsKHR(physical_,surface_,&fn,nullptr);std::vector<VkSurfaceFormatKHR>fs(fn);vkGetPhysicalDeviceSurfaceFormatsKHR(physical_,surface_,&fn,fs.data());auto sf=fs[0];for(auto&f:fs)if(f.format==VK_FORMAT_R8G8B8A8_SRGB||f.format==VK_FORMAT_B8G8R8A8_SRGB){sf=f;break;}format_=sf.format;extent_=cap.currentExtent.width!=UINT32_MAX?cap.currentExtent:VkExtent2D{uint32_t(width_.load()),uint32_t(height_.load())};uint32_t count=std::clamp(cap.minImageCount+1,cap.minImageCount,cap.maxImageCount?cap.maxImageCount:cap.minImageCount+2);VkSwapchainCreateInfoKHR ci{VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR};ci.surface=surface_;ci.minImageCount=count;ci.imageFormat=format_;ci.imageColorSpace=sf.colorSpace;ci.imageExtent=extent_;ci.imageArrayLayers=1;ci.imageUsage=VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;ci.imageSharingMode=VK_SHARING_MODE_EXCLUSIVE;ci.preTransform=cap.currentTransform;ci.compositeAlpha=VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR;ci.presentMode=VK_PRESENT_MODE_FIFO_KHR;ci.clipped=VK_TRUE;vkok(vkCreateSwapchainKHR(device_,&ci,nullptr,&swap_),"swapchain");vkGetSwapchainImagesKHR(device_,swap_,&count,nullptr);images_.resize(count);vkGetSwapchainImagesKHR(device_,swap_,&count,images_.data());views_.resize(count);for(size_t i=0;i<images_.size();i++){VkImageViewCreateInfo vi{VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};vi.image=images_[i];vi.viewType=VK_IMAGE_VIEW_TYPE_2D;vi.format=format_;vi.subresourceRange={VK_IMAGE_ASPECT_COLOR_BIT,0,1,0,1};vkok(vkCreateImageView(device_,&vi,nullptr,&views_[i]),"swap view");}createDepth();createPipeline();fbs_.resize(images_.size());for(size_t i=0;i<images_.size();i++){VkImageView at[]={views_[i],depthView_};VkFramebufferCreateInfo fi{VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO};fi.renderPass=pass_;fi.attachmentCount=2;fi.pAttachments=at;fi.width=extent_.width;fi.height=extent_.height;fi.layers=1;vkok(vkCreateFramebuffer(device_,&fi,nullptr,&fbs_[i]),"fb");}}
 void createDepth(){VkImageCreateInfo ii{VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO};ii.imageType=VK_IMAGE_TYPE_2D;ii.extent={extent_.width,extent_.height,1};ii.mipLevels=1;ii.arrayLayers=1;ii.format=VK_FORMAT_D32_SFLOAT;ii.tiling=VK_IMAGE_TILING_OPTIMAL;ii.usage=VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT;ii.samples=VK_SAMPLE_COUNT_1_BIT;ii.sharingMode=VK_SHARING_MODE_EXCLUSIVE;vkok(vkCreateImage(device_,&ii,nullptr,&depth_),"depth");VkMemoryRequirements mr{};vkGetImageMemoryRequirements(device_,depth_,&mr);VkMemoryAllocateInfo ai{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};ai.allocationSize=mr.size;ai.memoryTypeIndex=memType(mr.memoryTypeBits,VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);vkok(vkAllocateMemory(device_,&ai,nullptr,&depthMem_),"depth mem");vkBindImageMemory(device_,depth_,depthMem_,0);VkImageViewCreateInfo vi{VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};vi.image=depth_;vi.viewType=VK_IMAGE_VIEW_TYPE_2D;vi.format=VK_FORMAT_D32_SFLOAT;vi.subresourceRange={VK_IMAGE_ASPECT_DEPTH_BIT,0,1,0,1};vkok(vkCreateImageView(device_,&vi,nullptr,&depthView_),"depth view");}
 void createPipeline(){VkAttachmentDescription ad[2]{};ad[0].format=format_;ad[0].samples=VK_SAMPLE_COUNT_1_BIT;ad[0].loadOp=VK_ATTACHMENT_LOAD_OP_CLEAR;ad[0].storeOp=VK_ATTACHMENT_STORE_OP_STORE;ad[0].initialLayout=VK_IMAGE_LAYOUT_UNDEFINED;ad[0].finalLayout=VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;ad[1].format=VK_FORMAT_D32_SFLOAT;ad[1].samples=VK_SAMPLE_COUNT_1_BIT;ad[1].loadOp=VK_ATTACHMENT_LOAD_OP_CLEAR;ad[1].storeOp=VK_ATTACHMENT_STORE_OP_DONT_CARE;ad[1].initialLayout=VK_IMAGE_LAYOUT_UNDEFINED;ad[1].finalLayout=VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;VkAttachmentReference cr{0,VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL},dr{1,VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL};VkSubpassDescription sp{};sp.pipelineBindPoint=VK_PIPELINE_BIND_POINT_GRAPHICS;sp.colorAttachmentCount=1;sp.pColorAttachments=&cr;sp.pDepthStencilAttachment=&dr;VkRenderPassCreateInfo rp{VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO};rp.attachmentCount=2;rp.pAttachments=ad;rp.subpassCount=1;rp.pSubpasses=&sp;vkok(vkCreateRenderPass(device_,&rp,nullptr,&pass_);}

 void createPipelineFixed(){ }
